### ISSUE TITLE
Blocks network traffic

### ISSUE THREAD

**Issue by alervd** [basil00/Divert#111]
Hello,

1.1.8 worked fine.  I've tried updating to 1.3 version and got the following issue: WinDivert blocks all HTTP network traffic (I use the following filter: "tcp and (tcp.DstPort == 80 or tcp.SrcPort == 80)"). I.e. all HTTP sites becomes unavailable. HTTPS sites continues to work in my browser. 

This is when I'm on LAN. But, if I switch to Wi-Fi, issue is gone. 

I suspect some sort of conflict between WinDivert and my LAN device driver (Realtek PCIe GBE Family Controller). We can't reproduce this issue on another PCs we have. I've also tried to uninstall all antiviruses/firewalls/etc. No luck.

My LAN device driver: Provider: Realtek, Date: 3/23/2017, Version: 10.16.323.2017.
OS: Windows 10 with the latest updates (1709).

**Comment by TechnikEmpire** [comment]
@alervd Can you provide more details, like the actual code sample? What are you doing with the handle you use that filter on? Is it a drop handle? What about checksum calculation, etc etc. Https of course will be let through because you're only targeting port 80 and not 443. There's quite a few things that could be going on, so showing source code is the only real way to properly resolve the issue here.

**Comment by basil00** [comment]
The first thing to check is whether you are recalculating checksums for *all* packets, even unmodified packets.  See the [WinDivert1.2 upgrade guide](https://github.com/basil00/Divert/wiki/WinDivert-1.2-Upgrade-Guide), which also applies to version 1.3.

This may explain the symptoms you see, since the Wi-Fi adapter may not support checksum offloading.

**Comment by alervd** [comment]
checksums
