### ISSUE TITLE
Implementing PPS (passthru)

### ISSUE THREAD

**Issue by kai07** [basil00/Divert#117]
Hi,

I was hoping someone here could guide me in the right direction on how to implement a packet per second variable in the passthru source. 

The code snippets I have found seem to be linux based, and some of the functions do not appear to have a direct replacement on Windows. (eg. gettimeofday)

One snippet I was looking through was http://1wt.eu/tools/udp-test/rcv.c

I'm essentially just trying to get a simple integer that counts each packet in the while loop of the passthru. 

```
static int count = 1;
count = 0;
    while (TRUE)
    {
        // Read a matching packet.
        if (!WinDivertRecv(handle, packet, sizeof(packet), &addr, &packet_len))
        {
            continue;
        }
		
		WinDivertHelperParsePacket(packet, packet_len, &ip_header, NULL, NULL, NULL, NULL, &udphdr, NULL, NULL);
		
		if (ntohs(udphdr->SrcPort) == 389)  { 
			count++;
			printf("count: %u\n",count);
			continue;
		} 
		
        if (!WinDivertSend(handle, packet, packet_len, &addr, NULL))
        {
            fprintf(stderr, "warning: failed to reinject packet (%d)\n", GetLastError());
        }
    }
```

The above is what I currently have, it does count each packet, but I do not know how to reset each second, I thought this would be a fairly trivial task but I have been unable to get it working. 

Thank you.

**Comment by TechnikEmpire** [comment]
You should be at least using the SendEx function to send so that the call completes immediately.

As far as pps why don't you just use an int to hold your packet counts, use chrono high resolution clock to get your start and end times, then cast the difference to seconds or milliseconds then divide your packet count accordingly to get your estimation after so many loops/iterations. I of course assume you are using c++11 not plain c.

If you're trying to create a running average that keeps running and printing indefinitely then that's different.

**Comment by kai07** [comment]
The example I posted isn't exactly clear since I was using the if statement to test the PPS count. 

But in the real example I wanted to be able to use the PPS number to begin filtering LDAP. (udp sourceport 389)

So for example: 
if (ntohs(udphdr->SrcPort) == 389 && count >=25000)  { continue; }

Where the count would be updated each second with the current packets per second. 
 
> I of course assume you are using c++11 not plain c.

I'm modifying the example passthru.c, I don't know anything about C outside of learning how to put together the udphdr and sourceport from other windivert snippets. So I honestly don't know which version it is. Sorry

**Comment by basil00** [comment]
@TechnikEmpire writes...
> You should be at least using the SendEx function to send so that the call completes immediately.

This should no longer be necessary.  Since WinDivert 1.3.0 the `WinDivertSend` also completes immediately.

**Comment by TechnikEmpire** [comment]
@basil00 Thanks for that correction. Good to know.

**Comment by basil00** [comment]
@kai07 This is more of a general programming question rather than a WinDivert issue.

The general gist of the idea is ok, sans bugs: you keep a counter and increment it for each packet received.  Then you need to get time information, in which case you need to lookup the appropriate Windows API calls.

Don't forget there are different versions of WinDivert.  The `passthru` code for WinDivert 1.4 does not compute checksums, but this is required for WinDivert 1.3.  Version 1.4 has not been released yet.

Also, `continue` will bypass the call to `WinDivertSend` meaning the packet won't be re-injected.

**Comment by basil00** [comment]
@TechnikEmpire Yeah that was a major performance bug in versions 1.2 and earlier.  At the time I could not fix it since I had no way to sign the driver.  But it appears you figured out the workaround anyway.
