### ISSUE TITLE
WDK 10 / Visual Studio 2017

### ISSUE THREAD

**Issue by ferdiozturk** [basil00/Divert#118]
Could you please provide (/update to) WDK10 + VS2017 ready solution/project files? Thanks

**Comment by TechnikEmpire** [comment]
Is it really that hard to do this yourself? I've never tried but I see many people asking for this and I just can't bring myself to believe that it's anything more than a trivial 5 minute exercise to do this yourself.

**Comment by TechnikEmpire** [comment]
@sgeto That's debatable. I can reconstruct the entire caffe-opencl project from plain source files and patch it to run on windows in an evening, I'm pretty sure someone with experience can reconstruct this project in 5 minutes. My 2 cents for whatever it's worth. Also I don't see what downside there is to the automated upgrade assistant. That's what it's designed to do.

**Comment by TechnikEmpire** [comment]
5 minutes or not, it's definitely something people are capable of doing on their own. Do it and submit a pr. I dunno maybe it's just me, I normally don't tag authors of libraries asking them to hold my hand and do everything I need done for me.

**Comment by sgeto** [comment]
> Also I don't see what downside there is to the automated upgrade assistant.

I've (tried to) automatically migrate/upgrade quite a lot of project files in my time and my expirience is that the resulting project files aren't as complete as they should be. Especially when migrating stuff from VS2008 or older or when project files are very heavily modified.
Try and see, there's always something weird or not working properly.

> 5 minutes or not, it's definitely something people are capable of doing on their own.

On that, we agree.

I wanted to hand in a pr a while ago but time is just so scare...

**Comment by basil00** [comment]
Upgrading the build system is on the TODO list but not a priority, especially since the current build system produces perfectly functional drivers.  But maybe it is time to look into this since 1.4 is released.

The main requirements are: (1) the build tools are free (e.g., do not require a paid license from Microsoft), (2) must build drivers that support Windows 7 and above out-of-the-box, (3) must not introduce new dependencies, and (4) the primary build system should in the form of a script similar to the existing `msvc-build.bat` file (but updated to VS2017+WDK10).  A more standard GUI build can exist alongside the script.

**Comment by majibow** [comment]
For your information MS Visual Studio 2017 Community Edition is free. I'd also like to take this opportunity to register my interest for this... +1.

**Comment by basil00** [comment]
Be our guest --- any help would be greatly appreciated.

**Comment by PantherJohn** [comment]
@basil00 Hi!Why not precompile these packages is what I was wondering. That saves A LOT LOT of time.

**Comment by PantherJohn** [comment]
@basil00 sorry I didn’t quite notice that. Thanks.

**Comment by basil00** [comment]
WinDivert 1.4.3 is now available for testing: https://github.com/basil00/Divert/releases/tag/v1.4.3

The new release is designed to be compatible with all major compilers, including Visual Studio 201X:

* The v1.4.3 `WinDivert.dll` library no longer depends on any version of `MSVCRT*.dll`
* The v1.4.3 binary package includes a `WinDivert.lib` import library.

**Comment by kelvinomolumo** [comment]
Very nice...Thanks @Basil00. My work really depends on your project

**Comment by TechnikEmpire** [comment]
Start the clock I'm making a WDK 10 project from scratch, I said ~5 minutes lets see.

**Comment by TechnikEmpire** [comment]
Done

![image](https://user-images.githubusercontent.com/11234763/43369323-ff08dd86-9339-11e8-9e6c-d1305267b668.png)

**Comment by basil00** [comment]
Does this include building the driver though?

**Comment by TechnikEmpire** [comment]
@basil00 Yeah. I'll push stuff to a fork and tag you when I get around to it. also I'm looking at pulling the ALE layer stuff in, trying to think of a way to build onto the existing API with that though. Any suggestions?

**Comment by basil00** [comment]
Adding new layers like ALE is non-trivial which is the main reason it has not been done before.  I am investigating/researching the idea of adding "transport" layer for WinDivert 2.0, since this mostly fits into the existing API and it is possible to incorporate some ALE-like features (via flow contexts) like process IDs.  Pure ALE layer support is another idea, but also inherits much of the complexity.

**Comment by TechnikEmpire** [comment]
Yeah I've started reading the documentation. I can definitely see it being a non-trivial task if the driver intends to automatically merge or associate somehow the ALE information with individual packets but if it were incorporated independently and left up to driver users to do the association externally it doesn't look that difficult (those are usually my famous last words btw).

**Comment by basil00** [comment]
> I am investigating/researching the idea of adding "transport" layer for WinDivert 2.0,

This turns out to be a bad idea.  The WFP transport layer offers some marginal benefit (filtering before IPSec encryption) but adds too much complexity.  For example, because the IP header is not yet formed (for the outbound path) some information is represented in a (possibly arbitrary size?) `controlData` buffer, which would somehow need to be threaded to and from the user application.  Furthermore, there are things like the transport endpoint handle, which I am not sure if it is safe to pass to user space.

The ALE layers are much more promising, and I already have a prototype that supports the `FLOW_ESTABLISHED` layer, and this may form the basis of WinDivert 2.0 (I might open a wishlist issue soon).  One problem is that the ALE layers are stateful, which does not fit with WinDivert's stateless API, so the "flow" layer is restricted (essentially sniff and read-only).  But nevertheless, this layer is very useful since the processID is available, and this can be associated with a network 5-tuple, allowing the user application to filter the traffic at the usual `NETWORK` layer.  I may investigate supporting other ALE layers as well.

**Comment by kelvinomolumo** [comment]
Nice nice @basil00. Thanks. Really looking forward to WinDivert 2.0 then

**Comment by basil00** [comment]
I've added a VS2015 build system which also includes building the drivers.  It may also work for later versions of VS but this is untested.

The VS binaries themselves are also not properly tested yet, so should be considered *unstable*.

The plan is to eventually retire the old WDK7 build system.  The MinGW build system will probably still remain as the main build system for the non-`sys` binaries since it does not depend on the VS runtime libraries.
