### ISSUE TITLE
What will the two same windivert program run

### ISSUE THREAD

**Issue by JmSeason** [basil00/Divert#120]
if the two same windivert program run at the same time, the filter rules is the same, if one get the filtered data, the other one will not get the filtered data, is that right?

**Comment by basil00** [comment]
The handle with the higher priority (see the `priority` value for `WinDivertOpen`) will get the packets first.  The handle with the lower priority will only see any matching packets the first handle injects.

If the two handles have the same priority, only one of the handles will get any packets.  This is not ideal, and maybe should be revisited at some point.

**Comment by basil00** [comment]
It turns out the driver already has a mechanism to handle this which I had forgotten about.  Basically, the user priority is mapped to the upper bits of an internal 32-bit priority.  The lower bits are assigned via an internal counter.  This means that two Windivert handles with the same user priority will likely (sans wrap-around) have two different internal priorities, meaning that both will see packets.

**Comment by TechnikEmpire** [comment]
Don't you love it when you've been working on a project for so long that you start to forget it? :D

**Comment by basil00** [comment]
Yep, I vaguely remembered it was a problem but had forgot about the fix.  I only noticed because I had to revisit the code for the `REFLECT` implementation.
