### ISSUE TITLE
WinDivertHelperEvalFilter returns invalid results/undefined behavior for ifIdx filters?

### ISSUE THREAD

**Issue by smithjacobj** [basil00/Divert#125]
I've got some functionality where I'm trying to ID which interfaces are currently being filtered to disable network offload functions (e.g. Large Segment Offload). However, if I specify just `ifIdx` filters with a dummy packet (more about that in a second...), I get strange results. Here's the function, to start:

```
/**
 * \brief test if the specified interface index matches the filter
 */
static bool WinDivertIfaceMatchFilter(const char *filter_string, int if_index)
{
    bool match = false;

    WINDIVERT_ADDRESS if_addr = {};
    if_addr.IfIdx = if_index;

    uint8_t dummy[4] = {4, 4, 4, 4};

    match = WinDivertHelperEvalFilter(filter_string, WINDIVERT_LAYER_NETWORK,
                                      dummy, sizeof(dummy), &if_addr);
    if (!match) {
        int err = GetLastError();
        if (err != 0) {
            SCLogWarning(SC_ERR_WINDIVERT_GENERIC,
                         "Failed to evaluate filter: 0x%" PRIx32, err);
        }
    }

    return match;
}
```

As an aside, it would be nice if I could test this without specifying a dummy packet; it seems like that check is just so that the code doesn't have to check `pPacket != NULL` for specific flags later in the eval function.

The test functionality (I've disabled the fail condition so it prints all the failures):
```
static int SourceWinDivertTestIfaceMatchFilter(void)
{
    struct testdata {
        const char *filter;
        int if_index;
        bool expected;
    };

    struct testdata tests[] = {
            {"true", 11, true},
            {"ifIdx=11", 11, true},
            {"ifIdx==11", 11, true},
            {"ifIdx!=11", 1, true},
            {"ifIdx!=11", 11, false},
            {"ifIdx=3", 4, false},
            {"ifIdx=11 || ifIdx=5", 5, true},
            {"ifIdx=11 || ifIdx=4", 5, false},
            {"ifIdx<3 || ifIdx>7", 8, true},
            {"ifIdx<3 || ifIdx>7", 5, false},
            {"ifIdx>3 or ifIdx<7", 5, true},
            {"ifIdx>3 && ifIdx<7", 5, true},
            {"ifIdx>3 && ifIdx<7", 1, false},
            {"(ifIdx > 3 && ifIdx < 7) or ifIdx == 11", 11, true}};

    size_t count = (sizeof(tests) / sizeof(tests[0]));

    for (size_t i = 0; i < count; i++) {
        struct testdata test = tests[i];

        bool actual = WinDivertIfaceMatchFilter(test.filter, test.if_index);
        if (actual != test.expected) {
            printf("WinDivertIfaceMatchFilter(\"%s\", %d) == %d, expected %d\n",
                   test.filter, test.if_index, actual, test.expected);
            // FAIL;
        }
    }
    PASS;
}
```

The test failures:
```
WinDivertIfaceMatchFilter("ifIdx=11", 11) == 0, expected 1
WinDivertIfaceMatchFilter("ifIdx==11", 11) == 0, expected 1
WinDivertIfaceMatchFilter("ifIdx!=11", 11) == 1, expected 0
WinDivertIfaceMatchFilter("ifIdx=11 || ifIdx=5", 5) == 0, expected 1
WinDivertIfaceMatchFilter("ifIdx<3 || ifIdx>7", 5) == 1, expected 0
WinDivertIfaceMatchFilter("ifIdx>3 && ifIdx<7", 5) == 0, expected 1
WinDivertIfaceMatchFilter("(ifIdx > 3 && ifIdx < 7) or ifIdx == 11", 11) == 0, expected 1
```

I'm trying to poke around at this, but I haven't yet grokked the full filter compilation (especially how boolean conditions are handled/flattened). Plus the information for [building with WDDK](https://www.reqrypt.org/windivert-doc.html#building) is old and I'm trying to figure out what the `build` command in the `wddk-build.bat` is (is the WDK7 required, or is 10 OK?) My target is MinGW 32-bit at the moment, and I only plan on building the DLL anyway since that appears to be where the helper code lives (sensibly so).

**Comment by kelvinomolumo** [comment]
I think you are using the function wrong. You can't actually assign anything to the WINDIVERT_ADDRESS when receiving or evaluating a packet. The struct simply returns the packet details. That's why you pass it as a pointer to WinDivertHelperEvalFilter or WinDivertRecv. If you are targeting a specific Adapter Index everything should be done in the filter section. The filter specify the kind of packet you want to drop/sniff/capture. Anyway thats my understanding. I will let @basil00 explain better. I might be wrong

**Comment by TechnikEmpire** [comment]
I started to look into this, digging through the sources. My initial suspicion was that the ifidx would be in network/big endian order. However, I don't see any order swapping going on in the filter eval function. It literally just takes the raw value and does an equality comparison directly. If you want to be certain you could just a nthol on your idx assignment and see if the tests pass.

The docs mention that the ifidx variable is ignored on outbound packets, and the default initialization state of your header(s) is would default to outbound, but as far as I can see that shouldn't affect the eval function. 

That's about where I quit looking into it because I've run out of time. Basil will know what's up.

**Comment by TechnikEmpire** [comment]
I recreated this with WinDivert 1.3 and all the tests passed. @basil00 Maybe you're right, some mixing of incompatible structures here.

**Comment by smithjacobj** [comment]
Thanks, I'll make sure I've got everything up to 1.4.1 and clean out my build files just in case I have stuff lurking...

Thanks for mentioning the conditional edge case @basil00, I'll definitely take that into consideration.

**Comment by smithjacobj** [comment]
Tested with everything cleaned up, definitely looks like a 1.3/1.4.1 structure mixup. Apologies!
