### ISSUE TITLE
WinDivert can't work in windows10?

### ISSUE THREAD

**Issue by song0320** [basil00/Divert#133]
i have tested webfilter.exe in examples and created a BlackList.txt insert www.avatar-edu.cn 
run with webfilter.exe BlackList.txt  command
it's worked with windows7 but in windows10 after run i can visit then web still and network speed is so slow，how can i solver

**Comment by TechnikEmpire** [comment]
Can you post your specific build of Windows 10? Run->winver.

WinDivert works fine on Windows 10. Also which version of WinDivert and which release variant are you using? Theres different versions signed by different sponsors.

**Comment by basil00** [comment]
One thing is that `webfilter.exe` does not work for HTTPS sites.  What output does `webfilter.exe` print 
when it is running?  It should at least print the URLs that are accessed (over HTTP), and whether they are blocked or not.

**Comment by song0320** [comment]
@TechnikEmpire 
winver show my windows10 ver is 
![1cc02bc313541aeb1b999244b039efae](https://user-images.githubusercontent.com/19398025/41265101-17dfea5c-6e23-11e8-8b97-6e883ee19060.jpg)

and my WinDivert is last version 1.4 download from https://reqrypt.org/windivert.html

**Comment by TechnikEmpire** [comment]
@song0320 I would listen to whatever @basil00 says, he's the library author, I'm just some dude. Your Windows 10 build is ahead of mine, so unfortunately I'm not able to test in the same environment.

**Comment by song0320** [comment]
@TechnikEmpire  i found some things 
1.i was use powershell,it's not work
2.when i visit webpage with ie it can't work

**Comment by basil00** [comment]
I'd almost forgotten, but `webfilter.exe` does not work with Internet Explorer.  See [here](https://github.com/basil00/Divert/blob/ae25f274698c02292a2337ba9361442961113944/examples/webfilter/webfilter.c#L466) for the reasons.  In particular, Internet Explorer violates the assumption that the `the Host header immediately follows the GET/POST line`.

So this is a known bug of `webfilter.exe`, but can't be properly fixed since it often means the host header is in the next packet.  But `webfilter.exe` is mainly just for introducing the basics of WinDivert, not a serious HTTP/S filtering tool.  For the latter, perhaps @TechnikEmpire can help.

**Comment by TechnikEmpire** [comment]
@song0320 if you're comfortable using c# I can point you to a package and examples that use WinDivert for complex http/s content filtering. Supports websockets as well.

If not, I used to maintain a c++ library but I pretty much abandoned that once I migrated to c# and it needs work. It's called HttpFilteringEngine (in my repo list). I've been planning to build a new rewrite of it using boost::beast but it might be a while before I get to that.

As @basil says, this gets complicated quickly. You basically need to host a local web server and leverage the higher-level tcp/ip constructs (sockets etc) in order to let the existing stack handle message building, error handling, etc, and then filter at that level. Trying to filter at the packet level with any consistency or deep inspection is going to give you headaches and be extremely difficult. You're going to need to basically replicate large portions of TCP and SSL stream operations manually, and there's no sense in doing that when the operating system already gives you those things.

**Comment by song0320** [comment]
@TechnikEmpire thanks ， i'm using c# and i 'm looking  the repo of HttpFilteringEngine, but i haven't find out examples,can you give me some one?

**Comment by TechnikEmpire** [comment]
Hey @song0320, the c# project is here.

https://github.com/TechnikEmpire/CitadelCore.Windows

There's a console application test/example in that repo that demonstrates usage.

You can also find it on nuget here:

https://www.nuget.org/packages/CitadelCore.Windows/

This project uses WinDivert 1.3 and is under the same license (lgpl).
