### ISSUE TITLE
WinDivert stops network traffic on ESXi VMs not using virtual E1000 adapter

### ISSUE THREAD

**Issue by smithjacobj** [basil00/Divert#138]
* WinDivert 1.4.1
* ESXi `6.7.0 (Build 8169922)` host
* Windows 10 x64 client (occurs on other versions)
* vShield endpoint driver removed

This is a really specific issue, but I thought I should bring it up. When any adapter option is chosen for the VM other than E1000, e.g. E1000e or VMXNET3, running the `passthru` application or another WinDivert-based application will block all traffic matching the filter string.

This seems related to the whole WFP infinite loop/"impostor" situation, but that seems strange for the E1000e selection, which is supposed to emulate a hardware device like E1000. VMXNET3 is its own can of worms, and I'm not familiar how packets enter the network stack there.

**Comment by basil00** [comment]
First try upgrading to WinDivert version 1.4.3.  Version 1.4.1 has a bug that may cause packets to have the wrong checksums.

**Comment by smithjacobj** [comment]
Thanks, this appears to have resolved the issue - I hadn't even noticed there was an update despite visiting the home page on unrelated business multiple times this week...

This now works on E1000e and VMXNET 3, so I assume there's some bug/feature of E1000 that fixes checksums or doesn't trigger the bug.

Thank you!

**Comment by basil00** [comment]
The exact cause of the bug is still a mystery, but was probably a misinterpretation of how WFP handles packet injection and checksum offloading.  It apparently affects some NICs but not others.  Furthermore, the bug went unnoticed for about 6months then there was a flood of reports, so something recent may have triggered it (windows update?)

As for announcing new versions of WinDivert, I am not sure of a good solution.  Normally I just publish to github and update the website.
