### ISSUE TITLE
Simple connection tracking offloading

### ISSUE THREAD

**Issue by ValdikSS** [basil00/Divert#140]
Some software (as [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI)) does not need to intercept every packed specified in the filter string, but only some of the first packets in every TCP session.

I propose to implement a feature similar to what could be found in hardware NAT implementations: a way to notify the driver that next N packets or next N seconds the packets from a src ip/dst ip and src port/dst port set should not be copied to the userspace. This will reduce CPU load and eliminate unnecessary userspace packet processing.

**Comment by kelvinomolumo** [comment]
Maybe not what you want but intercepting just the TCP SYN packet is it not enough?

**Comment by ValdikSS** [comment]
@kelvinomolumo no, I need mostly data packets, but not all of them. For example, for HTTPS connection GoodbyeDPI needs only first 2 packets in a TCP session.

**Comment by ValdikSS** [comment]
@TechnikEmpire >can you shed some light on how manipulating only the first two packets in http defeats DPI and does it apply to https?

Most DPI could be circumvented by pseudo-fragmenting first TLS ClientHello packet.

>Also I think the request itself is sort of asking the project to go against it's own nature.

I have to disagree. Linux's iptables + nfqueue allows you to do the same, but it also incorporates TCP connection tracking. You can write an iptables rule to divert only the first 3 packets to the userspace in the exact TCP flow, for example.

>In my case, I set flags for each packet flow using the src/dst ports as the flag array index to track individual packet flows and my CPU usage floats at a cool 0, occasionally spiking to 1 then right back down and that's with 8 threads reading in packets. I don't see a performance dip but of course that's just my experience.

People with Gbit links at home (somewhat common in Russia and Ukraine) complain that GoodbyeDPI consumes CPU when they use programs which use port 80 or 443 (like cloud sync).

**Comment by basil00** [comment]
> Some software (as GoodbyeDPI) does not need to intercept every packed specified in the filter string, but only some of the first packets in every TCP session.

Yes, this would be a useful feature I'd also like to have.  However, it requires some form of connection tracking that is (afaik) not available at the WFP network layer where WinDivert operates (since the network layer is meant to be stateless).

However, I think flow tracking is available WFP transport layer which may be supported in future versions of WinDivert.  This may also allow process ID support.  It will require a major implementation effort though, so maybe next year.

In the meantime, it might be possible to "emulate" connection tracking, although it is a bit more complicated:

* Open a WinDivert handle `H` that intercepts outbound SYNs to TCP port 443.
* When H intercepts a SYN with source port `X`, open a new handle `H1` with filter `outbound and !tcp.Syn and tcp.SrcPort == X`.  Re-inject the SYN.
* Intercept first data packet, close `H1` and re-inject the transformed packets using `H`.
* Might need some extra logic for handling network errors, e.g., timeouts, etc.

**Comment by ValdikSS** [comment]
@basil00 
>However, it requires some form of connection tracking that is (afaik) not available at the WFP network layer where WinDivert operates (since the network layer is meant to be stateless).

At least for my scenario, I'm happy with userspace-controlled "dumb" connection tracking inside the driver. Not a proper connection tracking, but just a simple packet tracking with defined source/destination IP address, protocol and source/destination ports, and flags. A way to inform the driver of something like: "from now on, do not copy packets from 192.168.1.10 to 1.1.1.1 TCP source port 1234 destination port 80 with TCP flag ACK or PSH,ACK, but copy all other packets from this IP/port set."

**Comment by basil00** [comment]
> "from now on, do not copy packets from 192.168.1.10 to 1.1.1.1 TCP source port 1234 destination port 80 with TCP flag ACK or PSH,ACK, but copy all other packets from this IP/port set."

In effect these are additional filter conditions.  So one way to do it is to extend WinDivert to support dynamic modification of the filter string after the handle has been opened, e.g. something like an `WinDivertSetFilter` API call.  However, this has its own implementation complications, and it might be more worthwhile to focus on transport layer support at first.

I am planning a refresh of WinDivert in the second half of 2018, so will take these ideas into consideration.

**Comment by basil00** [comment]
The `WinDivertSetFilter` idea adds too many complications so will not be implemented in the next version.  (I originally intended `WinDivertShutdown` to accept individual events, but even this limited case causes an explosion in complexity).

Flow/connection tracking has been implemented in a different layer, which does not really help for filtering at the network layer (except by the application itself).  Adding connection tracking to the network layer is also very complicated, so unlikely to be implemented.  The ugly (but functional) way to do this is explained [here](https://github.com/basil00/Divert/issues/140#issuecomment-407367763) if performance is critical.

There will be new `tcp.Payload[idx]` filter expressions, which may help select more narrow subsets of traffic for some applications.  But might not be useful for TLS+SNI since the relevant data typically appears in the second packet.

The next WinDivert will be include a "batching mode" that should help cut overheads even if all traffic is diverted.
