### ISSUE TITLE
Changing source ipv4 addr

### ISSUE THREAD

**Issue by arcylte** [basil00/Divert#143]
Hi there. I’m not really sure if this is an issue and I apologise in advance if I could be posting this in a more apropriate place. I am attempting to modify the source IP address of a udp packet. Using the helperparsepacket function to grab the ipheader and modifying the destination address has proved fine, however changing the source address hasn’t seemed to have done anything. Upon further inspection all my outbound packets which ip headers remain unchanged are being parsed with the machines local network ip address. I am attempting to modify the ip header to make the packet look as if it has came from a different Internet ipv4 address. Am I going about achieving this the wrong way? I thought I was on the right track, although it seems I am certainly not. Any advice regarding how I might go about achieving this would be thoroughly appreciated

**Comment by basil00** [comment]
I am not sure if it is possible to spoof the source address using WinDivert.  I think Windows routes outbound packets based on source IP address, but don't quote me on that, so I am not sure what happens if `ip.SrcAddr` is set to a address that does not match any network interface.

That said, it might be possible by injecting into the `FORWARD` layer.

Even if you get it working with WinDivert, packets with spoofed source addresses will likely be dropped by your ISP/network, see [BCP38](https://tools.ietf.org/html/bcp38).
