### ISSUE TITLE
handle SIGSEGV in KernelBase.dll ( GetOverlappedResults() )

### ISSUE THREAD

**Issue by hbs24** [basil00/Divert#145]
Hi!
Im working on vpn client which the main work is to "extract" udp packets.
(just to make it clear: every packet catch by openWinDivert is a UDP packet which encapsulate TCP/UDP packet...the "inner" dst_ip is of our local network and need to be replace by the "outer"  ip_dst )

to change the inner ip dst i use the parsePackect function twice:
first: 
WinDivertHelperParsePacket(packet, packet_len, &ip_header,  NULL, NULL, NULL, NULL,&udp_header, &ppData, &pDataLen);
//when the packet is the UDP (that encapsulate the "real" packet)
then: 
UINT32 dst_addr = ip_header->DstAddr; //save the client ip
and finally parse it agin like this:
WinDivertHelperParsePacket(ppData, pDataLen, &ip_header2,NULL, NULL, NULL, NULL,NULL, NULL, NULL)
//ppData is the pointer to payload from first parsing (and start the new header...)
now im replace the ip_dst: 
ip_header2->DstAddr=dst_addr;
doing checksum: 
WinDivertHelperCalcChecksums(ppData, pDataLen,&addr,0);
and send the modified packet like this:
WinDivertSend(handle, ppData, pDataLen,&addr, NULL);

my issue:
its work fine for a while (but slow...) and crashed for some reason i cant figured it out
...trying to running as debug (gdb) it mention GetOverlappedResults()...
im not using threads but it seems that a new thread somehow created at the dll...a second before the segmention fault.

please help me ):
***
notes:
1. The first project done with pydivert and work fine but slow...so the idea was to convert the network process to c code using windivert.
2. Im load  the dll with loadlibary() and  use getprocaddr() function for the windivert functionality .
3. minGW & cygwin 
4. Im new coder..specially  with the WIN env.

**Comment by basil00** [comment]
I didn't notice any obvious problems with the code snippet.  The crash could be caused by some generic issue like stack overflows or corruption, or perhaps there is some incompatibility with Cygwin.  The WinDivert dll does not spawn any threads, but perhaps the Cygwin runtime does.

Can you compile and run the WinDivert same programs?
Can you please post a more complete snippet including the declarations for `ppData`?

The `GetOverlappedResult` WinAPI function is called by both `WinDivertRecv` and `WinDivertSend`.  Which of these functions are crashing?  (or is it something else?)

**Comment by basil00** [comment]
a) The problem is that pydivert uses an out-of-date version of WinDivert (see [here](https://github.com/ffalcinelli/pydivert/issues/36)).  The 'priority' feature only works if all programs are using the same version.

b) It probably more optimal since python is interpreted.  However, for most low/medium throughput applications it would not make much of a noticeable difference.  It'd probably only matter if you plan to process multiple MB/s.
