### ISSUE TITLE
passthru.exe still not working out-of-box for the latest windivert on Xen virtual machine

### ISSUE THREAD

**Issue by haohaolee** [basil00/Divert#160]
**problem**: I tested passthru.exe from WinDivert 1.4.3A on a Citrix Virtual Desktop which is Xen Virtual Machine. Once I opened passthru.exe, all TCP traffic is blocked. Even a sync packet couldn't be sent out. I think it is similar to #134 , but no matter pseudo checksum is enabled or not, passthru .exe just couldn't work. However, If I disable the  checksum offload in the XEN network adapter driver, everything works right away.

**environment**: 
![image](https://user-images.githubusercontent.com/238419/47770921-37cffb00-dd1c-11e8-9d5d-92730bc80c61.png)
![image](https://user-images.githubusercontent.com/238419/47770931-46b6ad80-dd1c-11e8-8010-42d05baf018b.png)
![image](https://user-images.githubusercontent.com/238419/47770995-8087b400-dd1c-11e8-894b-9fd0c2188732.png)

**Comment by basil00** [comment]
> However, If I disable the checksum offload in the XEN network adapter driver, everything works right away.

WinDivert-1.4.3 will only inject packets with "full" checksums, and never injects packets that use checksum offloading.  Even if the user application attempts to inject a packet with "pseudo" checksums, the DLL will calculate the full checksums before passing the packet to the driver for the actual injection.

So I wonder if there is a bug in the Xen network driver?  For example, if the network driver incorrectly assumes that packets *must* have offloaded checksums (if checksum offloading is enabled), then this would explain the symptoms observed here.

Otherwise, it seems you have discovered a temporary workaround: *disable checksum offloading*.

**Comment by haohaolee** [comment]
Thanks for the explanation. Two things I still don't quite understand

1. How could we explain: The Xen driver works well before WinDivert starts, but after that, we need to disable checksum offload?

2. and more, if WinDivert always calculates the full checksum, why does the option "Checksum offload" affect this?

**Comment by basil00** [comment]
Whether or not to use checksum offloading depends on meta data attached to each packet.  If the NIC driver ignores this and calculates based on global settings, it will end up with the wrong TCP/UDP checksums so packets will be dropped.  So (1) is explained since WinDivert injected packets will have full checksums, whereas the NIC driver is assuming checksum offloading based on the global setting, and (2) is explained since disabling offloading globally means the NIC driver is assuming full checksums, which now matches WinDivert injected packets.

I only mention this theory because it matches the observed symptoms.  The problem could be caused by something else, and I would not rule out a bug in WinDivert.  However, if this were a WinDivert bug, then we'd expect other NIC drivers to also be affected.

**Comment by basil00** [comment]
Was this issue resolved?  Or does Xen+WinDivert+Offloading still not work?
