### ISSUE TITLE
[8.1] Fail to open WinDivert device

### ISSUE THREAD

**Issue by r4sas** [basil00/Divert#165]
Hi.
I'm using WinDivert in GoodbyeDPI package.
But after installing latest updates I have error with loading of driver.

Then I try test netdump program from latest release archive and got error:

```
> netdump.exe true
error: failed to open the WinDivert device (5)
```

**Comment by r4sas** [comment]
btw, I think that issue had same problem: https://github.com/ValdikSS/GoodbyeDPI/issues/101

**Comment by TechnikEmpire** [comment]
You need to run as administrator. The error codes returned by windivert are windows error codes.

https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-


Error 5 is access denied.

**Comment by r4sas** [comment]
Ok, if I try run as admin I got error 2.

**Comment by r4sas** [comment]
Thx @ValdikSS, he said to stop and delete old 1.3 service. After that filter started without problems.

**Comment by TechnikEmpire** [comment]
Damn I didn't know diff versions of windivert running can cause these kinda of issues.

**Comment by r4sas** [comment]
I did not know at all that there was a similar service that remains to work in the system when the application is stopped: D

**Comment by basil00** [comment]
> I did not know at all that there was a similar service that remains to work in the system when the application is stopped :D

This is by design since there can be more than one application using the WinDivert service.  So if one application deletes the service then it can prevent new applications from working.  Also, afaik, there is no way to delete the service automatically when all client applications have closed.

That said, I am not sure what caused error (2) in this case.  It could be that the service was using a different copy of the windivert driver that had since been deleted, but hard to say for sure.
