### ISSUE TITLE
When WinDivertSend is used under high traffic load, TCP connection establishment starts to fail

### ISSUE THREAD

**Issue by avikama** [basil00/Divert#166]
We encountered this issue after running some traffic load testing on our application (which uses windivert) - we read the packet using WinDivertRecv, and then write the packet back using WinDivertSend.

The symptoms we encountered were, under medium-high load, we start receiving TCP RST on channel establishment. It seems that the socket who's packets we were diverting decided to stop accepting new connections. 

The limit we reached (we tested Kerberos port, 88) was at about ~35 connections per seconds (we used 200 concurrent workers) we start receiving these RSTs.

 This only happens when:
1. The packets are received and then sent using WinDivert
2. On a virtual environment (we tested VMWare, with both E1000 and VMXnet NICs)

Finally, we opened a WinSock trace to try and find the error code traced from the socket (attached).
Also attached is the CPP wrapper we used in our code.
[wincosck.evtx.zip](https://github.com/basil00/Divert/files/2861068/wincosck.evtx.zip)
[diversion_device.zip](https://github.com/basil00/Divert/files/2861069/diversion_device.zip)

**Comment by basil00** [comment]
Thanks for the report.  I am not sure what the problem is, but I have a few questions that would help narrow down the cause:

1. Is the problem reproducible with the `passthru` sample that is included in the WinDivert distribution?
1. Is the problem reproducible in other environments, or only your specific VMWare setup?
1. Is the problem reproducible with other servers/protocols besides Kerberos?

**Comment by TechnikEmpire** [comment]
@avikama does your application start to deadlock on windivert functions when this situation arises? Or does it just carry on and the connections fail?

I'm experiencing a similar issue using the Ex variants but my application seems to start to deadlock when this apparent limit is hit. Still investigating so my issue may be entirely unrelated.

**Comment by basil00** [comment]
@TechnikEmpire Do you also get TCP RSTs or just the deadlocking issue?

**Comment by TechnikEmpire** [comment]
@basil00 I haven't checked. I just noticed today that I can deadlock it if I open a bunch of tabs in chrome. I'm still investigating. I'm also rewriting the C# wrapper for 2.0 API to see if it's resolved in the unreleased version.

**Comment by TechnikEmpire** [comment]
I'm wondering if this is OS specific because I've specifically tested under heavy load before without issue with the same windivert version so maybe people reporting should include that too if not already.

**Comment by basil00** [comment]
The original issue regards inbound connections, so it might be something else.  Although, not handling overlapped I/O correctly may cause these kinds of problems.  This is why it is important to verify the problem using `passthru` to rule out any bug in the user application.

**Comment by TechnikEmpire** [comment]
@basil00 Disregard my remarks. It was code outside of WinDivert causing issues. My bad, sorry for the noise.

**Comment by avikama** [comment]
Hi @basil00 !

The issue did not reproduce with the passthru sample (and we tried with even higher traffic loads). 
We changed out code to use the WinDivertRecv and WinDivertSend instead of the async versions (using a thread per read-write loop), and the issue went away in our code as well.

I guess we got the async code wrong or something? Anyway, this is more than good enough for us.

Thanks for the help!

**Comment by TechnikEmpire** [comment]
Yeah I must be doing this wrong. Can you shed some light on this @basil, for us noobs who don't understand overlapped IO? Would be greatly appreciated.

**Comment by basil00** [comment]
Maybe there is a bug in the async versions.  To test this, I'd recommend trying the `streamdump` sample (which uses my implementation of overlapped I/O) and see if the problem persists.  Ideally you should comment out the `printf`s to minimize other factors like console I/O synchronization.  It's not a 100% reliable test since I am not sure how well `streamdump` itself can hold up under load...

One common mistake with overlapped I/O is reusing `OVERLAPPED` structures for more than one send/recv, or recycling them before the recv/send requests have completed.  In the original `DiversionDevice.cpp` code, I think this could happen if more than one thread is calling `send`/`recv` at once.

**Comment by TechnikEmpire** [comment]
Thanks for that? Is the sole purpose of the cleanup function in the example only to mop up the malloc'd overlapped for the sendex call?

**Comment by TechnikEmpire** [comment]
@basil00 That is to say, do you only need to call the `cleanup` function because you alloc and fire off an `OVERLAPPED` in `sendEx`, meaning that you could drop that call without sending out an overlapped on the `sendEx` call? Thanks in advance.

**Comment by basil00** [comment]
It's been a while since I looked at the code, but it does appear to be mopping up the malloc'ed `OVERLAPPED` structures from `SendEx`.  In principle, the send operation could complete at any time, and we do not want to wait, so the code uses I/O Completion Ports.

Actually I am not even sure that `SendEx` ever pends in modern versions of WinDivert, so the code is needlessly complicated.  But part of the purpose of that sample was to show overlapped I/O in action...
