### ISSUE TITLE
Can we modify `ADDR` struct to be a little friendlier?

### ISSUE THREAD

**Issue by TechnikEmpire** [basil00/Divert#167]
Hey, I've been working on updating WinDivertSharp and the new struct layout for `ADDR` in the 2.0 api is really beating me up. In C#, since it's baby's first language, we can't define struct member lengths with the same ease. I have do a bunch of gymnastics using field offsets and explicit struct layouts, fake unions and just really ugly stuff trying to replicate what exists in C.

Is there any specific reason for the dense packing in `ADDR`? Is there any way we can loosen that up a little bit? I have yet to determine with absolute certainty whether or not it's simply my lack of knowledge, of if I'm hitting a limitation in the language.

**Comment by basil00** [comment]
Which part is the problem, the bitfields or the union?  I'm not sure about C#, but if the language has no support then the address could be treated as a byte blob and fields extracted manually.  It might be a bit of a chore to implement because there are so many fields now.

As for the reasons, it's mainly implemented the way it is because it's the natural way of doing it in C/C++.  Keeping it dense also reduces the amount of memory copying required, which is not a bad thing, although it has never been benchmarked.

**Comment by TechnikEmpire** [comment]
Ok cool, thanks. Yeah I guess you're right I'll just ship over a byte array worst case.
