### ISSUE TITLE
name of process in filter

### ISSUE THREAD

**Issue by showf68** [basil00/Divert#169]
Hello and thank you for the new update of WinDivert 2.0.
I saw that you added the possibility of getting the processID.
Could you please give me an example of a filter that will only get the Internet traffic generated by chrome.exe

Thanks again

**Comment by TechnikEmpire** [comment]
lmao

**Comment by basil00** [comment]
Since 2.0 is brand new there is not much in terms of examples to point to.  The closest is [Tallow's redirect.c](https://github.com/basil00/TorWall/blob/b8c2dc198d9eb83164beed327054de72ad1e4576/redirect.c) that uses the `SOCKET` layer to *whitelist* traffic from Tor's PID.

To filter only traffic from applications named `chrome.exe`, you need to:

1. Open a `SOCKET` layer handle and examine all outbound `CONNECT` events.
2. For each new `CONNECT` event, map the PID to the application name: `OpenProcess` -> `GetProcessImageFileName` and check for `chrome.exe`.  If it matches, add the network 5-tuple to a blacklist, else add the 5-tuple to a whitelist.

Then separately:

1. Open a `NETWORK` layer handle.
2. For each network packet, either (1) reinject if the 5-tuple is whitelisted, or (2) filter if the 5-tuple is blacklisted.

There are various optimizations to this basic idea, depending on how complicated you are willing to make the project.

One complication is that there is a race between the `CONNECT` event at the `SOCKET` layer and the SYN packet (or connectionless equivalent) at the `NETWORK` layer.  Thus you may need to "pend" handling of the SYN until the `CONNECT` event is handled.  Tallow does this.
