### ISSUE TITLE
binary packages WinDivert-2.0.0-rc-C.zip no work on win10

### ISSUE THREAD

**Issue by bronze1man** [basil00/Divert#184]
I download WinDivert-2.0.0-rc-C.zip from this page https://reqrypt.org/windivert.html

binary packages WinDivert-2.0.0-rc-C.zip no work on win10
WinDivertOpen return error: 0x800b010c A certificate was explicitly revoked by its issuer.

binary packages WinDivert-2.0.0-rc-A.zip works on that machine.

**Comment by eyalk5** [comment]
Also doesn't work on windows server 2012R2 (either version A or C) , and on windows server 2008R2

**Comment by basil00** [comment]
That's odd since the driver file has 3 signatures: a SHA-1 and SHA-256 from the company, and a SHA-256 from Microsoft.  Windows 10 should be using the one from Microsoft, which shouldn't be revoked (unless Microsoft revoked it?).

I tried the C variant but everything works for me.  But maybe it is because I am using a VM with secure boot disabled?  In the meantime, switch to a A or B variants.

**Comment by basil00** [comment]
This should be fixed in version 2.1.0 since the release no longer includes a SHA1 signature.
