### ISSUE TITLE
WinDivert work far worse on some computers

### ISSUE THREAD

**Issue by eyalk5** [basil00/Divert#188]
Hi,

The problem is as follows:
We have two servers that should behave quite the same. Both are virtual DCs that are 2008r2  with 2 cores of 2ghz, started from the same template. They both are on the same ESX , same subnet.  We wrote a script that opens at once 5000 TCP sessions and then waits for answers and closes the sessions. 
We try it on tcp port 88 with 4 threads and 30 seconds wait (from a remote server of course).

The script was used to compare the situation in which windivert is active, and in which it isn't. If windivert isn't active, then all the responses to the sessions (ACK) are received in time. If windivert is active, we have major differences between server G(good) and B(bad). 

In G, with windivert - during the run of passthru.exe, the situation remains the same(5000 successes). But in  B we have 1000-3000 failures depending on some unknown factors. We think that if lsass is busy or cpu is high, we would have more failures. Running passthru on higher proirity makes things better. The failures are sessions that we get no asnwer to or that are actively rejected(RST). 

It applies to both versions of windivert(The results are a bit better in windivert 2 but not significantly) 

Attached is the test script and the code of it. We hope that some other people could reproduce this situation and help us shed some light on this mysterious behavior. It would be nice if you simply run it and could report even a good result. 

testsock.exe addr 88 30 
[testsock.zip](https://github.com/basil00/Divert/files/3195303/testsock.zip)

Eyal Karni
Preempt

**Comment by eyalk5** [comment]
Let me know if you have any helpful suggestion(or you want extra info). We might run perfview on both computers as the next step.

**Comment by basil00** [comment]
Thanks for the report.

> In G, with windivert - during the run of passthru.exe, the situation remains the same(5000 successes).

Hmmmm, this probably indicates that the issue is not WinDivert alone, but maybe WinDivert in some combination with some setting or other software.  If it were purely a WinDivert issue, then all machines will probably be effected.

> The failures are sessions that we get no asnwer to or that are actively rejected(RST).

Neither WinDivert nor `passthr.exe` generate RST packets.  So it is probably useful to first track down who/what is generating these packets, which might give some clue regarding the problem.

Some other things to try/investigate are:

* Try with different filters, e.g., `inbound`, `outbound`, `random8 <= 128`.  How does this affect the performance?
* Examine the `Timestamp` of the captured packets.  You can compare this against `QueryPerformanceCounter` to determine how long the packets were queued for before received by the user application.
* Check things like kernel memory usage (non-paged pool).  Perhaps there is a resource issue.

**Comment by eyalk5** [comment]
Thanks for the suggestions. The errors are probably sent by winsock (afd driver) because the queues are filled completely( I guess). All it is expected to send is ack and then we close it.

**Comment by basil00** [comment]
It sounds like a resource issue, and not a problem with WinDivert directly.  If anything, it could be a indirect problem, e.g., WFP injected SYN packets require more resources/processing, which cause the problem.  But this is also something WinDivert can't do anything about.

Is syn flood protection enabled?

**Comment by basil00** [comment]
No further information, so closed.  For general performance see issue #52.
