### ISSUE TITLE
Forward Layer filtering not working with windivert 1.1.2

### ISSUE THREAD

**Issue by vinayakkg** [basil00/Divert#19]
Hi ,
  Previously i was using windivert 1.0 in my application for filtering packets in forward layer.When i changed to 1.1.2 i am unable to filter packets in forward layer.Previously i set priority as -31768 and layer as  forward for getting packets from forward layer but now i am unable to divert open with that priority.Even if i set the -1000 priority and layer as forward still i am unable to get data from forward layer.Hope for your help and advice..
Thanks,

**Comment by TechnikEmpire** [comment]
@vinayakkg @basil00  I know this is an old thread, but I've implemented the capability to identify the process behind a single packet (inbound or outbound) in the .NET wrapper for WinDivert. Now, yes the wrapper is written in ugly M$ VC++, but the code inside the functions is using the plain C Win API. There are four of them for the combinations (IPV4+UDP, IPV6+UDP, IPV4+TCP, etc), they're all overloads called GetPacketProcess, if you're interested in doing this yourselves.

https://github.com/TechnikEmpire/Divert.Net/blob/master/src/Diversion.cpp#LC186

**Comment by basil00** [comment]
Thanks @TechnikEmpire.  I wonder if there is a (theoretical?) data race between the TCP table and the process (e.g. if the process terminates).  I think this was the justification Microsoft used for not including process information directly in the Network layer for WFP.  Data race or not, such functionality is still useful enough for many applications.

**Comment by TechnikEmpire** [comment]
@basil00 You're definitely going to see the situation you describe if you're trying to do this on packets sniffed rather than diverted and reinjected. Even I made this mistake in my C# example and I wrote the code! lol so it's easy to misuse.

However, in most cases, intercepting, then doing to the process query, then reinjecting will force the process to keep alive and listening for the data, so the table query will return accurate data. Worst case, by the time you query, the process is gone and you'll get a result of "SYSTEM" (either 0 or 4 PID).

It's definitely not 100% though, you're right. Ideally you do not want to be asking for process information on every single packet anyway, but rather you would create objects to track flows, and do these queries once per flow. This will drastically cut down CPU usage and allocations and increase the accuracy of identifying processes.
