### ISSUE TITLE
Use of not, ! and () parenthesis in filter language 

### ISSUE THREAD

**Issue by majibow** [basil00/Divert#192]
Filter Language Error.

I came across an interesting issue... may be a known issue but I couldn't find it in search.

`"not true"` is fine 
`"(false)"` is fine 
`"not  (true)"` is **not** fine and neither is `"!(true)"`

Don't dismiss this, think.

`"not (tcp.DstPort=80 or tcp.DstPort=443)"` is **not** fine 
`"!(tcp.DstPort=80 or tcp.DstPort=443)"` is **not** fine

These should probably work.

As a workaround for anyone coming across this issue, play with the logic a little bit e.g. 
`"(tcp.DstPort!=80 and tcp.DstPort!=443)"` is fine 

If updating the filter language is not an option, perhaps this information should be in the FAQ and in the API doc.

**Comment by basil00** [comment]
As per the documentation, the `not` token is syntactic sugar part of the test, and **not** a Boolean operator.  This is by design and has been this way since WinDivert 1.0.

The reason is because filters really use a three-valued logic: `TRUE`, `FALSE` and `IRRELEVANT`.  For example, a UDP packet is `IRRELEVANT` for `tcp.DstPort == 80`

> "`not (tcp.DstPort=80 or tcp.DstPort=443)`" is not fine

Should this filter match a UDP packet?  There are two interpretations:

1. `not IRRELEVANT = IRRELEVANT`: so *should not* match
2. `not IRRELEVANT = TRUE`: so it *should* match

Different people have different opinions, so it a source of confusion.  To avoid this, `not` is not a Boolean operator.

Wireshark uses the (2.) interpretation, which also means that (unlike WinDivert) `not X == Y` and `X != Y` are **not** equivalent filter expressions.

> As a workaround for anyone coming across this issue, play with the logic a little bit e.g.
"`(tcp.DstPort!=80 and tcp.DstPort!=443)`" is fine

Assuming they want the (1.) interpretation.

The other way is to use conditional expressions `(X? Y: Z)` which are "procedural" and use the (2.) interpretation for negation.
