### ISSUE TITLE
Modify outgoing UDP packet size

### ISSUE THREAD

**Issue by fgrueninger** [basil00/Divert#193]
Hi,
I'm trying to modify the packet size of outgoing UDP packets with `passthru.c`.
I thought it's enough to just set the packet_len and call WinDivertHelperCalcChecksums:

```c
if (!WinDivertRecvEx(handle, packet, packet_len, &packet_len, 0,
        addr, &addr_len, NULL))
{
    fprintf(stderr, "warning: failed to read packet (%d)\n",
        GetLastError());
    continue;
}

// limit packet size to 200 bytes
// when I set this, I'm getting "warning: failed to calculate checksum" and "warning: failed to reinject packet (122)"
packet_len = 200;

if (!WinDivertHelperCalcChecksums(packet, packet_len, &addr, 0)) {
	fprintf(stderr, "warning: failed to calculate checksum\n");
}

// Re-inject the matching packet.
if (!WinDivertSendEx(handle, packet, packet_len, NULL, 0, addr,
        addr_len, NULL))
{
    fprintf(stderr, "warning: failed to reinject packet (%d)\n",
        GetLastError());
        }
```
However, I'm getting both `warning: failed to calculate checksum` and `warning: failed to reinject packet (122)` when I set `packet_len`. The original packet is around 500 bytes.

What could be wrong with my code?

**Comment by basil00** [comment]
WinDivert uses [system error codes](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-), so `122` is `ERROR_INSUFFICIENT_BUFFER` which gives you a hint.

The problem is that you did not modify the length in the [UDP packet header](https://en.wikipedia.org/wiki/User_Datagram_Protocol#Packet_structure).  In effect, you are trying to inject a 500byte UDP packet, but only provide the first 200bytes, hence the errors.
