### ISSUE TITLE
Trojan Warning

### ISSUE THREAD

**Issue by abeljinming** [basil00/Divert#225]
Hi

I always be prompted there is a trojan in WinDivert when download from https://reqrypt.org/download/WinDivert-2.2.0-A.zip or from Github. 

Is it real?

**Comment by basil00** [comment]
> Is it real?

No.

The problem is that some malicious software use WinDivert, and some lazy antivirus just flag WinDivert files rather than the malicious software itself.  You should report the problem to your antivirus as a false detection and send them a link to this thread.

**To AV Authors: How to Detect Which Program is using WinDivert**

WinDivert is not malicious and there are 100s of legitimate programs using WinDivert.  Please flag the malicious program itself and not WinDivert files.

The program that is using WinDivert can be easily detected using multiple methods, including:

* Examine open handles for `\device\windivert`
* Check for WinDivert driver events in the event log.
* Use `WinDivertOpen` with the `WINDIVERT_LAYER_REFLECT` layer.  This gives detailed information about what programs are using WinDivert, and how (e.g., the layer, flags, filter string, etc.)

Please see https://github.com/basil00/WinDivertTool for an implementation.

**Comment by abeljinming** [comment]
many thanks.  (reported)
