### ISSUE TITLE
Can't re-inject modified NETWORK_FORWARD layer packet

### ISSUE THREAD

**Issue by shamper** [basil00/Divert#244]
Hello,

I am currently trying to modify a packet on the NETWORK_FORWARD layer then re-inject the modified packet on the same layer. Trying to do so yields no results, as in, the packet goes unmodified (checked via Wireshark).

Though looking through the examples, this does not seem the correct way to do it. So I opened two handles, one on the NETWORK_FORWARD layer and one on the NETWORK layer. My goal here was to listen for the packet on the NETWORK_FORWARD layer, copy it then drop it (by not calling send after I received it), then modify it and inject it with the NETWORK handle. However, this also yields no results, as the packet is still sent through even when I have correctly filtered it out and was sure not to invoke send on it.

I am curious as if this is a technical limitation with the NETWORK_FORWARD layer, or an error on my end (most likely so :)).

I appreciate your time.

**Comment by basil00** [comment]
Probably this is interaction with the Windows NAT, which is the usual problem when using the `FORWARD` layer.

I recall that the NAT injects the packets on the outbound/`NETWORK` layer, so you can intercept the packets there.  I can't quite remember how it works since this issue comes up too infrequently.  If you search through the issues you might find some more advice.
