### ISSUE TITLE
BSOD due to prolonged run time at an IRQL of DISPATCH_LEVEL

### ISSUE THREAD

**Issue by avikama** [basil00/Divert#257]
We encountered the following issue, using latest Windivert 2.2.0.
See attached file for stack trace information. 
[bugcheck.txt](https://github.com/basil00/Divert/files/5664887/bugcheck.txt)

**Comment by avikama** [comment]
We are working on getting the crash dump from the machine where this happened.

**Comment by romanblachman** [comment]
@basil00 any ideas on what could have caused this? this is the first time we are seeing BSOD.

**Comment by basil00** [comment]
According to the stack trace, the crash occurred when the driver called the `FwpsInjectNetworkSendAsync0` function.  This corresponds to packet injection on the outbound path.  The WinDivert driver itself does not use DPCs directly, so it is unclear what the cause is.

The packet injection code is largely unchanged since the original version of WinDivert (~10 years), so it is unclear if that is the problem.

Googling for the error code, it seems it can sometimes be caused by faulty hardware.  So is this problem isolated to one machine or does it occur with several users/machines?

Also, please provide other information: minidumps, what the user application was doing, Windows version.

**Comment by basil00** [comment]
I assume this issue was resolved.
