### ISSUE TITLE
Changing filter at runtime

### ISSUE THREAD

**Issue by vkrasnov** [basil00/Divert#260]
Hi,

I was wondering if it is possible to add the ability to change the windivert filter on an existing handle? Without the need to close and open a new handle.

Cheers,
Vlad

**Comment by basil00** [comment]
Such a feature is unlikely to be added, since there is not much benefit over opening a new handle, and it would introduce a lot of complexity.  It is also unclear how to treat packets that are queued by the old filter but unread by the program.  In the case of opening/closing a new handle, the user application can control how packets are handled in that case.
