### ISSUE TITLE
How can I assembly package if I modify package payload length

### ISSUE THREAD

**Issue by dengzibiao** [basil00/Divert#273]
In version 1.4.3, under certain conditions, I modify the package payload,for example:
WinDivertRecv(driver, packet, address, packetLen)
WinDivertHelperParsePacket(packet, packetLen, &_pip4Header, &_pip6Header, &_picmp4Header, &_picmp6Header, &_ptcpHdr, &_pudpHdr, &_pdataPtr, ref _dataLen)
I modify pdataPtr size ,the content is 'hello',and then
WinDivertHelperCalcChecksums(packet, packetLen, address,flags);
WinDivertSend(handle, packet, packetLen, address,  sendLen)

In all the execution，packetLen will not modify, still is 3, otherwise i modify length is 5
if I input '123', then output is 'hel',

**Comment by dengzibiao** [comment]
when I  modify package and modify ppIpHdr->Length = newLen * 256, then call WinDivertHelperCalcChecksums 
and WinDivertSend  use newlen the package send success, but then I loop receive package, the package payload length is sendLen - oldLen, forExample, input 1122112211, then set it to 'hello', send it success, then receive '12211', loop, then tcp client shut down

**Comment by basil00** [comment]
Changing the length of TCP packets is very hard, since you need to also adjust the `tcp.SeqNum` and `tcp.AckNum` for the rest of the lifetime of the stream.  I do not recommend it unless you know what you are doing.  It is much easier to redirect to a local proxy, e.g., see the [streamdump.exe](https://github.com/basil00/Divert/blob/master/examples/streamdump/streamdump.c) sample program.
