### ISSUE TITLE
Not receiving forward packets

### ISSUE THREAD

**Issue by micrak** [basil00/Divert#281]
I'm learning network basics and I decided to implement my own NAT.
It looks that WinDivert 2.2.0 provides everything to achieve my goal.

Here is my network topology:
![image](https://user-images.githubusercontent.com/5851387/131808185-341882cb-7614-4b7e-9181-d76d8df1b5a0.png)

Now I want to ping router from the [HyperV Virtual Machine]:
ping 10.0.15.1

In wireshark I'm capturing eth1 and I see the incoming ICMP packet from 10.0.0.220 to 10.0.15.1

However WinDivert receives nothing. This is my problem. Here is how I open WinDivert:
WinDivert.WinDivertOpen("icmp", WinDivertLayer.Forward, 30000, WinDivertOpenFlags.None);

Tried also with filter "icmp and udp and tcp" - still receiving nothing.

From other hand I can receive non-forward packets correctly when I ping 10.0.0.210:
WinDivert.WinDivertOpen("icmp", WinDivertLayer.Network, 30000, WinDivertOpenFlags.None);

I saw the documentation and it says that WinDivert has some issues when mixed with Windows NAT.
However, I should be able to receive the packages. Am I right?

My machine configuration:
- multiple network interfaces, including 3 VLAN adapters
- few HyperV virtual adapters
- two physical adapters (ethernet + wifi)
- Wireshark installed (I tried to remove wireshark driver (npcap), but it didn't help)

**Comment by basil00** [comment]
Generally I do not provide support for the forward layer since it is confusing and a lot of work.  But this is a common problem, where the packet ends up on an unexpected path, such as `OUTBOUND` instead of `FORWARD`.  This can occur with another WFP driver (e.g., Windows NAT) re-injects the packet on a different path, and I believe this is normal/expected behavior.

It is not really a WinDivert issue.  WinDivert is faithfully intercepting the packets where they appear.

**Comment by micrak** [comment]
Thank you for answer and explaination. Your project is a gem.
I need to learn more about kernel programming.
Why did you choose WDF over NDIS?
