### ISSUE TITLE
Unexpected behavior in parsing filter with ipv6

### ISSUE THREAD

**Issue by trudyhood** [basil00/Divert#285]
Hi,
I have encountered a strange issue that you may have an idea over it. I am working on a complex app that uses WinDivert. Let see my app as a black box. After 4 hours I have found out that these two phrases are different.

 ```c#
var filter = $"(ip or ipv6 ) and outbound and !loopback and (udp.DstPort==53 or (ipv6.DstAddr==:: or ipv6.DstAddr>::) or ({phraseX}))";
var filter = $"(ip or ipv6 ) and outbound and !loopback and (udp.DstPort==53 or (ipv6.DstAddr>=::) or ({phraseX}))";
```

Both phrases look the same, but if I use filter2, my app doesn’t work! It looks there is something wrong with “ipv6.DstAddr>=::”
Any idea?

by the time, I have fixed my issue by this!
`filter = filter.Replace("ipv6.DstAddr>=::", "(ipv6.DstAddr==:: or ipv6.DstAddr>::)");`

**Comment by basil00** [comment]
Thanks for the report.

This appears to be a bug in the filter compiler.  Since `::` is equivalent to the zero address, the test `ipv6.DstAddr>=::` will always be true for any `ipv6.DstAddr` value (since addresses are unsigned).  The filter compiler therefore optimizes the test into `true`.

However, the optimization is not semantically correct, since the test `ipv6.DstAddr>=::` can fail if the packet is not IPv6.  This is a bug that I will need to fix.

Replacing `ipv6.DstAddr` with `(ipv6.DstAddr==:: or ipv6.DstAddr>::)` effectively disables the buggy optimization.  You can also just use `ipv6` as the test.

**Comment by basil00** [comment]
Thanks for the report.  It should be fixed now.
