### ISSUE TITLE
WARNING : VirusTotal detects some weird things

### ISSUE THREAD

**Issue by Captain-FLAM** [basil00/Divert#309]
Hi everybody,

When I started to get in interest of WinDivert, I downloaded the executables to test quickly, then as my habits, I pass files by VirusTotal :

[WinDivert-2.2.0-A.zip](https://www.virustotal.com/gui/file/2a7630aac0914746fbc565ac862fa096e3e54233883ac52d17c83107496b7a7f)  
[WinDivert-2.2.0-B.zip](https://www.virustotal.com/gui/file/9314cc87a362476e71f0818399fea57d05fd75ab33019962ed909cc5919a234c)  
[WinDivert-2.2.0-C.zip](https://www.virustotal.com/gui/file/bb66d1a8fa068c91fd9ec0710288da882464552e211fa8f903c8f0185880f915)

More over than strange because when I compile by myself, I only get a suspicious **heuristic** result :

[WinDivert-Captain_FLAM.zip](https://www.virustotal.com/gui/file/4abd6a634cfbcdd0c7ad3a1bd27bb70b85ff5c3626f0a93c7ab0332f80c625a4/detection)

Fortunately, the **".sys"** files are (apparently) safes. (as I don't want to use a self-signed driver)

(Still a great project than inspire me to start an old dream...)

**Comment by basil00** [comment]
Some antivirus will flag WinDivert as malicious, but this is just noise and can be ignored.

The problem is that WinDivert is a very general tool that has many useful applications, but sometimes it is also used by malicious software.  This may cause some "lazy" AV implementations to incorrectly flag WinDivert itself.

To counter this, WinDivert attempts to discourage malicious use by (1) requiring Administrator just to use WinDivert, and (2) providing an API to make WinDivert use easily detectable ("good" AV software can easily use an API to see which programs are using WinDivert and how).
