### ISSUE TITLE
Iterate packets from WinDivertReciveEx buffer

### ISSUE THREAD

**Issue by prakashkolandaivelu** [basil00/Divert#325]
How to iterate over the each packet on the buffer received from WinDivertReceiveEx call, when the bytes are stored contiguously without delimiter? Is there any example which I can refer.

**Comment by majibow** [comment]
- You would use `sizeof(WINDIVERT_ADDRESS)` to iterate the address buffer, unless directly incrementing the pointer works (it might if the compiler knows the size). If directly incrementing the pointer works then you may have to `pAddrLen / sizeof(WINDIVERT_ADDRESS)` as the number of packets to iterate. And,

- WinDivertHelperParsePacket() to parse the packet buffer as per the documentation.
 _By default this function will parse a single packet. However, if either ppNext or pNextLen are non-NULL, then the pPacket parameter can point to a batch (>1) of packets (and packetLen can be the total length of the batch). In this case, the function will parse the first packet, and a pointer to the remaining packet(s) will be written to ppNext, and the remaining length will be written to pNextLen. This makes it convenient to loop over every packet in the batch as follows:_

**Comment by prakashkolandaivelu** [comment]
Thanks for reply. 
I was able to modify the passthru.c file to receive batch of packets and parse them with the WinDivertHelperParsePacket method. 
Requirement: Receive batch of packets , iterate , put them in an custom array and send it for processing with different module. All types of packets should be received and processed.
Limitation with above given approach: All the ethertype should be supported in the code and each packets will be parsed twice by receiver and existing packet parser also. or receiver and parser module should be merged.

Expected:
Should be able to iterate the packets with out parsing it.

Like the address of each packet is returned,  if the packet size is also returned, then without parsing the packets, the packets can be iterated. is that possible?

**Comment by majibow** [comment]
Unless I am mistaken, I believe the packets are returned as a continuous block of bytes. And packets have variable lengths.

Since you only care about length detection. You could strip out what you think is not necessary in [WinDivertHelperParsePacket()](https://github.com/basil00/Divert/blob/c26ec39465d775f49f5dfc77a2612a289e4e74ed/dll/windivert_helper.c#L465) and [WinDivertHelperParsePacketEx()](https://github.com/basil00/Divert/blob/134dd37bd0a87d3d236214e42edc1867b8911c6f/dll/windivert_shared.c#L363) copy paste both and write your own limited parser special case for offloading in your program. 

Or you could pass the pointer for the full buffer to the module where the parsing is happening and iterate with WinDivertHelperParsePacket() there only once per packet. `#include "windivert.h"` in the module.

Otherwise I'm not sure why you chose the batch receive method, just WinDivertRecv() one at a time.

**Comment by prakashkolandaivelu** [comment]
Batching is because, tools is based on inline packet processing. So the performance is important. Reading packet one by one will have more performance impact vs reading in batch.

**Comment by basil00** [comment]
As mentioned, `WinDivertHelperParsePacket` can be used to iterate through batches.  It is a fast function, and unlikely to be a bottleneck, especially compared to the receive operation.
