### ISSUE TITLE
Possible problem with the NO_CHECKSUM flag

### ISSUE THREAD

**Issue by eylonR** [basil00/Divert#43]
Hi,

I'm trying to write a simple program that receives all UDP packets and send them out without changing (passthru-like).

Also, I don't want the driver to touch/modify the checksums so I put the NO_CHECKSUM flag.

Now, I tried to send an outbound datagram with regular UDP socket. However, the target machine received the packet with invalid UDP checksum (Not zero. and IP checksum was right) and the listener didn't accept it!

Without WinDivert, or without the flag - the checksum is correct and the transfer works.

I'm using Windows 7, and the code I've used:

#include "windivert.h"
int main(){
     HANDLE h = WinDivertOpen("ip && udp", WINDIVERT_LAYER_NETWORK, 0, WINDIVERT_FLAG_NO_CHECKSUM);
     WINDIVERT_ADDRESS addr;
     UINT len;
     CHAR buff[10000];
     while (1) {
          WinDivertRecv(h, buff, sizeof(buff), &addr, &len);
          WinDivertSend(h, buff, len, &addr, NULL);
     }
}

Am I missing something?

**Comment by basil00** [comment]
> Now, I tried to send an outbound datagram with regular UDP socket. However, the target machine received the packet with invalid UDP checksum (Not zero. and IP checksum was right) and the listener didn't accept it!

This is normal behavior.  It is up to the caller of WinDivertSend() to ensure the packet has correct checksums.  This is actually a requirement of the underlying WFP packet injection functions on which WinDivertSend() is built.

Ideally there would be a way to enable checksum offloading for injected packets.  Maybe there is a way but I am not aware of it.

So in your example: the driver does not calculate the checksum because of the NO_CHECKSUM flag.  Furthermore, your userspace program does not calculate the checksum (does not call WinDivertHelperCalcChecksums()).  So the packet is injected with an invalid checksum which is rejected by the remote peer, as expected.

To fix this you need to call WinDivertHelperCalcChecksums() in your application.

**Comment by eylonR** [comment]
Sorry for the late answer.
Why we have to call the WinDivertHelperCalcChecksums()?
The original packet is created by a regular OS socket, that anyway calculates a checksum.
As I said, without WinDivert the packet is delivered correctly, so the original checksum is okay.

**Comment by basil00** [comment]
Usually (but not always) WinDivert receives outbound packets before Windows has calculated the checksum.  This is actually for efficiency, Google "checksum offloading" for more information.  As a consequence, the checksums may or may not be valid when the NO_CHECKSUM flag is specified.

For some reason Windows also requires injected packets to have valid checksums, regardless of the checksum offloading configuration.  Therefore you must always call WinDivertHelperCalcChecksums() (or calculate the checksums yourself) before injection via WinDivertSend().

**Comment by eylonR** [comment]
So, there is no way to determine if the original checksum is correct in user-space?
In that case, we may be reinject malformed packets without knowing that, don't we?

**Comment by basil00** [comment]
No, there is currently no way.  This is a weakness in the API.  However, it is usually not so serious as most applications intend to modify the packets, so need to recalculate the checksums anyway.
