### ISSUE TITLE
WinDivertSendEx / WinDivertRecvEx

### ISSUE THREAD

**Issue by Phyxion** [basil00/Divert#45]
I only tested the WinDivertSendEx method.

I'm trying to get these functions to work in C# and I'm having trouble with them. When I add the overlapped parameter (with the event set), I never have to wait (e.g., with WaitForSingleObject, or with the ManualResetEvent as the C# equivalent) as the event always seems signaled immediately after I call the method. 

I expected this behavior:
> Functions such as ReadFile and WriteFile set this handle to the nonsignaled state before they begin an I/O operation. When the operation has completed, the handle is set to the signaled state.

Do these methods work differently or is there a bug somewhere? If not, how is this supposed to work in WinDivert? I tried all possible variants to get the Overlapped to work in C# and I never get a callback or the wait to work.

**Comment by basil00** [comment]
The WinDivertWSendEx() and WinDivertRecvEx() functions are actually thin wrappers around the WinAPI DeviceIoControl() function, so should inherit the same semantics.

What is the reason for not waiting, e.g. error or data available?  If it's an error, which error?

**Comment by Phyxion** [comment]
I'm making the application multithreaded and the WinDivertRecv / WinDivertSend function weren't that great for the performance. When I switched to WinDivertSendEx (with a useless Overlapped object so no waiting at all) the CPU usage went from ~50% to ~3% while increasing the throughput. 

The event/wait for the Send method doesn't seem very useful to me, but for Recv you of course need it. If I were to wait for the RecvEx to complete in the while loop it's pretty much identical to the normal Recv method so I was thinking about using the event of the overlapped to signal that it can continue (so that the while loop on the RecvEx can also continue immediately). 

I did some additional testing and I got it somewhat working with BindIoCompletionCallback. The problem is that this callback isn't fired for every Recv? Do you have to set some result yourself on the overlapped? I also tried the GetOverlappedResult but I haven't continued with that as I'd rather use the callback. Maybe I'm using this all wrong, I haven't really done anything with this DeviceIoControl before and there isn't that much documentation on it either (in C# almost nothing besides some stuff in the .NET libraries).

**Comment by TechnikEmpire** [comment]
My 2 cents: I find this post confusing. You're saying you gained huge performance savings by switching to EX functions but that it's not useful, and you assume there's a bug because you never seem to have to wait for the async call. Showing some code, error #'s etc might help solve the confusion.

**Comment by Phyxion** [comment]
@TechnikEmpire You should really read my post better.

**Comment by basil00** [comment]
I am not sure what the problem is.

Are you using one OVERLAPPED structure & event object per call to WinDivertRecvEx()?  If not, then you may see the symptoms you describe.  ([reference](https://msdn.microsoft.com/en-us/library/ms686358(v=vs.85).aspx))

**Comment by Phyxion** [comment]
Yeah, I use one. I'll check that page, it looks like there is some useful information in it.

**Comment by TechnikEmpire** [comment]
@Phyxion To quote basil - "I am not sure what the problem is." So blaming my reading skills doesn't really work. Sounds to me like you're describing a perceived phantom (non-existent) problem due to a lack of understanding.

**Comment by edlau2** [comment]
Basil -

If it helps, I am using WinDivert w/the Ex functions with no problems - basically as a NAT router. I can provide some simple samples that illustrate two things- the ability to trap traffic from devices not on the local machine as well as using I/O completion ports. I use both with no issues. To the posters question, sometimes receives complete immediately, so that has to be handled - but most arrive at the completion routine. Once initial immediate completions are handled, everything else is handled by the completion routine. If you would like I can make some simple samples as time permits - I have a simple sample for ICMP traffic to illustrate #1 (trapping traffic from other machines on the network) and can easily expand it to incorporate completion routines and overlapped IO. Just offering to help :-)

I am doing this in C++, not C#, but conceptually it is identical.

Ed

**Comment by Phyxion** [comment]
@TechnikEmpire
The problem:
> When I add the overlapped parameter (with the event set), I never have to wait (e.g., with WaitForSingleObject, or with the ManualResetEvent as the C# equivalent) as the event always seems signaled immediately after I call the method.

I then tried the BindIoCompletionCallback which does seem to work most of the times. With the discription from @edlau2 I found why it didn't always work, it sometimes indeed seems to complete immediately. I didn't expect this and changed a few lines of code and the BindIoCompletionCallback seems to work OK now. 

About your useful statement:
> The **event/wait** for the Send method doesn't seem very useful to me.

I'm not saying that these methods aren't useful because they clearly are. All I'm saying is that I don't think it's very useful to know if the data is actually sent or not as there isn't much you can with that specific information. I'm also not assuming there is a bug, I'm just asking if this is a possibility or that I'm using it wrong (as I stated several times already).

@edlau2 I would really appreciate it if you could provide a small sample on how you do this exactly.

**Comment by TechnikEmpire** [comment]
@Phyxion I'm gonna ignore the rudeness and just point out where you're wrong and why I said this whole thread makes no sense. Of course sometimes your async recv (EX) return immediately, because it's more than reasonable to assume that a packet could be coming in and getting caught up by your filter so close to your wait call, that it's can only be perceived as immediate.

As for "All I'm saying is that I don't think it's very useful to know if the data is actually sent or not" - Again this is completely wrong. What happens if your send doesn't complete for some reason? The thread trying to make the send happen could infinitely be stuck on that operation. The whole purpose of the EX version in this case allows you to set a timeout for the operation, then have the thread step beyond the call (as it's never blocking), at which point you can react to and recover from a timeout event, avoiding every having a deadlock occur (if done correctly).

So again, your post is entirely wrong. Entirely. I came along to this thread because I watch this repository and was more than willing to help in any way that I can. From one abrasive personality to another, keep it under wraps when you're looking for help.

**Comment by Phyxion** [comment]
My apologies, I didn't mean any harm but it's just that you seem to skip over all the points I'm making. To give you some insight, I implemented overlapped in ReadFile/WriteFile a while ago and this was acting differently (in C# the [IOCompletionCallback](https://msdn.microsoft.com/en-us/library/a059s071%28v=vs.110%29.aspx) for it worked but not with WinDivert) and as I've never used these overlapped structures otherwise I asked here if this behavior is as expected or that I'm using it wrong (which seems to be the case).

> What happens if your send doesn't complete for some reason? The thread trying to make the send happen could infinitely be stuck on that operation.

Hmm, that makes sense indeed. I assume that WinDivert not have a timeout on the I/O operations, so that after, let's say 1 second, I should call [CancelIoEx](https://msdn.microsoft.com/en-us/library/aa363792%28v=vs.85%29.aspx) to stop WinDivert from getting stuck. I still have to read through the page from @basil00, it seems to have a lot of information I'm currently missing.

**Comment by TechnikEmpire** [comment]
@Phyxion Text communication sucks, lets chalk it up to that. Basil helped me by pointing me to the use of RecvEx here. https://github.com/basil00/Divert/blob/master/test/test.c around line 304. Not sure if that will help, for me it always makes it crystal clear when I just see something in action in the wild.
