### ISSUE TITLE
How to build sys

### ISSUE THREAD

**Issue by codeyash** [basil00/Divert#48]
build.exe is not found in latest WDK kit. I'm new to this.

I'm building a simple app using your awesome library. Can you guide how to build driver? 

DLL I able to build easily. Facing problem is in sys.

**Comment by basil00** [comment]
WinDivert exclusively uses Windows Driver Kit (WDK) Version 7.1.0.  This is mainly because (a) it's free, and (b) it generates a driver that does not depend on newer versions of the WDF framework.  The latter means that users would need to distribute a bloated "WDF co-installer" package in order for WinDivert to work on older versions of WIndows (including Windows 7).
