### ISSUE TITLE
Get Application name

### ISSUE THREAD

**Issue by codeyash** [basil00/Divert#50]
How to get which application is requesting tcp connection i.e. sending/receiving packets.

If we can get like
tcpConnected( APPINFO)
tcpClosed( APPINFO)

That will awesome. Or If possible please give me few ideas/code to implement this.

**Comment by TechnikEmpire** [comment]
This isn't something WinDivert provides or needs to provide. Windows has API's to do this. It's a lot of code. Post a question on StackOverflow because it's not a simple couple of lines of code in this case.

**Comment by basil00** [comment]
If you post on stackoverflow then please add a link here (so others with the same problem can find the solution).

As for WinDivert, the association with packets (or tcp connections) to processes (e.g. process ID) is the most requested feature.  I would implement it if it were possible, but AFAIK the Windows kernel does not associate process information to packets at the network layer.  I think the reason is because there is actually a race condition: the process may no longer exist (& even the process ID can be reassigned) by the time WFP (or WinDivert) receives the packet.

**Comment by TechnikEmpire** [comment]
I do this myself, it's easy and for TCP, you're safe to cache the result for a couple of seconds. This way you're not doing an expensive GetTcpTable2 call on every single packet. Will post some code.

**Comment by TechnikEmpire** [comment]
Actually, if you want @basil00, I can fork, create a basic application-level firewall example in the examples directory that does precisely this, then do a pull request? Your call.

**Comment by basil00** [comment]
Thanks @TechnikEmpire.  Perhaps first describe the solution in this thread?

**Comment by TechnikEmpire** [comment]
@basil00  Since Vista, the owning process is associated with any/all ports it has in use. https://msdn.microsoft.com/en-us/library/windows/desktop/bb485761(v=vs.85).aspx So you parse the headers in an incoming packet, then do a series of GetTcpTable2/GetExtendedUdpTable queries which return rows of ports in use and the described data structures described in the link. Once you've found your port, you've got the owning PID. From there you've got everything, PID executable name/location/etc.

**Comment by TechnikEmpire** [comment]
Note however that the last time I checked, mingw fails to define the additional dwOwningPid member of the structure. The struct is defined incorrectly, so you'll get errors with mingw using these calls.

**Comment by TechnikEmpire** [comment]
Oh and one last thing, about race condition/caching. I use a simple hash table and a timeout period on TCP packets but you can, once you have the PID, subscribe to the closing event of the process, so you'll know precisely when your cached PID lookup has expired and that PID will be reassigned to something else. I just chose the hash table with a small timeout because it works just fine for my use and is a lot less work. :)

**Comment by basil00** [comment]
@TechnikEmpire This sounds like a reasonable solution and might help @codeyash.  It would be nice if a sample of this idea were publicly available in some form.  Even if not as an official WinDivert sample per se, it would be good to have something I can link to.

**Comment by TechnikEmpire** [comment]
@basil00 I'll just whip up an example application, make my own repo for it and link back here.
