### ISSUE TITLE
webfilter example does not work on internet explorer ???

### ISSUE THREAD

**Issue by alle1974** [basil00/Divert#59]
That's very strange. I'm using the webfilter.exe example and it's working on Firefox and Chrome but on Internet Explorer does not block any address configured on the blacklist.txt.
Someone can help me to understand why ?

thanks

Alessandro

**Comment by basil00** [comment]
This is explained here: https://github.com/basil00/Divert/blob/master/examples/webfilter/webfilter.c#L451

Basically, IE puts the Host header last, whereas most browsers put it first.  The webfilter code expects it to be first, otherwise it will not block.

It is not worthwhile fixing the problem since the webfilter is not the correct way of doing things anyway.  To do HTTP filtering 'properly' you should use WinDivert to redirect packets to a local proxy server, and have the proxy server do the filtering.  This can be achieved by adapting the recently added [streamdump](https://github.com/basil00/Divert/blob/master/examples/streamdump/streamdump.c) sample program.
