### ISSUE TITLE
2 issues: failure to inject packet 87 and ip header = null

### ISSUE THREAD

**Issue by sardasanat** [basil00/Divert#66]
1. When I implement windivert similar to passthru example, that is creating fix multiple threads and simple filter pass all i.e "outbound", I never get "failure to inject packet 87" error. When I changed the code, creating thread only when packet is received  via WindivertReceive (shifted function to main thread) and declaring windivert handle as global variable, many non-tcp packets I get "failure to inject packet 87" error. When I strictly test just one tcp flow, I get no error. 

I pass packet parameters to thread creating a pointer to packet structure. Checking Wireshark, packets belonging to protocol LLMNR, SSDP, NBNS etc are the ones not getting reinjected. Can please let know why it doesnt reinject these packets or if I am implementing something incorrectly?

2. Quite occasionally packets are detected as ip header = null which I drop. Just to understand, which are packets whose ip header are null ?

**Comment by basil00** [comment]
Can you post some code that illustrates what you are trying to do?

> I pass packet parameters to thread creating a pointer to packet structure.

Are you sure that both threads are not sharing the same packet and `WINDIVERT_ADDRESS` buffers?  If one thread clobbers a buffer it could explain the packet injection errors.

> Just to understand, which are packets whose ip header are null ?

These are IPv6 packets I assume.  Any packet returned by WinDivert should be either IPv4 or IPv6.

**Comment by sardasanat** [comment]
Dear Basil, Thank you for your reply. Please find following code, Basically I divert and delay every outbound packet , using a delay algorithm before re-injecting packet back.

" Are you sure that both threads are not sharing the same packet and WINDIVERT_ADDRESS buffers? If one thread clobbers a buffer it could explain the packet injection errors"
   I am not sure, I was thinking it could be cause of high packet input rate. But when I test it with higher packet input rate eg. 0.1 ms per packet, for single defined flow, it does not  give injection errors. 

//CODE
list mylist = NULL;
int debug = 0;//0=false,1=true
int flowNo =0;//Flow ID
#define MAXBUF  0xFFFF
HANDLE handle;
LARGE_INTEGER Frequency;

// data structure for windivert diverted packet to thread  
typedef struct{ 
 PVOID packet;
 UINT packet_len;
 WINDIVERT_ADDRESS addr;	
 int rand;
 LARGE_INTEGER Start;
} DATA,*PDATA;


int __cdecl main(int argc, char **argv)
{
      
       HANDLE thread;
	unsigned char pac[MAXBUF];
	UINT pac_len;
	WINDIVERT_ADDRESS add;
	LARGE_INTEGER StartingTime;
	PDATA param;
	DWORD id;
	
	if (argc != 2)
    {
        fprintf(stderr, "usage: %s filter\n", argv[0]);
        exit(EXIT_FAILURE);
    }
	
	MakeNullList(&mylist);    
        // packet delay algorithm
	InitializeRainbow(); 
       srand((unsigned) time (NULL));
       QueryPerformanceFrequency(&Frequency);
	// Divert traffic matching the filter:
    handle = WinDivertOpen(argv[1], WINDIVERT_LAYER_NETWORK, 0, 0);
    if (handle == INVALID_HANDLE_VALUE)
    {
        if (GetLastError() == ERROR_INVALID_PARAMETER)
        {
            fprintf(stderr, "error: filter syntax error\n");
            exit(EXIT_FAILURE);
        }
        fprintf(stderr, "error: failed to open the WinDivert device (%d)\n", GetLastError());
        exit(EXIT_FAILURE);
    }	
	// Create thread when packet received
	while(TRUE)
	{
				
		if (!WinDivertRecv(handle, pac, sizeof(pac), &add, &pac_len))
			{
			fprintf(stderr, "warning: failed to read packet (%d)\n", GetLastError());			
			continue;
			}	
		QueryPerformanceCounter(&StartingTime);	// storing start time of thread execution
		param = (PDATA) malloc(sizeof(DATA));
		if (param == NULL)
		{
			printf("failed to allocate memory");
		}
		//param->handle=handle;
		param->rand=rand();
		param->Start=StartingTime;
		param->packet=pac;
		param->addr=add;
		param->packet_len=pac_len;
		
		
		thread = CreateThread(NULL, 0, (LPTHREAD_START_ROUTINE)divert, (LPVOID)param, 0, &id);
		if (debug == 1) printf("\n  in main, id = %lu",id);
		if (thread == NULL)
		{
			fprintf(stderr, "failed to create thread (%d)\n", GetLastError());
		}		
		
		CloseHandle(thread);
	}
  
	return 0;
}


static DWORD divert(LPVOID arg)
{   
	
	HANDLE divert = handle;
	PDATA pam = (PDATA) arg;  	 
	//HANDLE hand = pam->handle;
	PVOID pac = pam->packet;	
       UINT pac_len = pam->packet_len;
        WINDIVERT_ADDRESS add = pam->addr;	
	int rand = pam->rand;
	PWINDIVERT_IPHDR ip_header;
        PWINDIVERT_TCPHDR tcp_header; 
	LONGLONG delay = 0;    
	list identified; 	
	//struct timeval tv2,tv;    	    
	LARGE_INTEGER StartingTime = pam->Start;
	LARGE_INTEGER EndingTime, TimeStamp, ElapsedMicroseconds;	
	typedef struct{  
		UINT32 saddr;
		UINT32 daddr;
		UINT16 source; 
		UINT16 dest;
	} PTHARGS;
	PTHARGS p;
	
	free(pam);
		
	//
	TimeStamp = gettimestamp(StartingTime,Frequency);
	
       // Parse packet IP 
	WinDivertHelperParsePacket(pac, pac_len, &ip_header, NULL, NULL, NULL,
		&tcp_header,NULL, NULL, NULL);
	
	if (ip_header == NULL)
		{
		if (debug == 1) printf("\nip header == NULL");   
		printf("  Skipping packet\n"); 
		return 0;
		}
	if (ip_header != NULL)
		{
			p.saddr = ntohl(ip_header->SrcAddr); 
			p.daddr = ntohl(ip_header->DstAddr); 
			
		}
	if (tcp_header != NULL)
		{
			p.source = ntohs(tcp_header->SrcPort); 
			p.dest = ntohs(tcp_header->DstPort);
		}
	
	// Identify packet flow
	if (!EmptyList(mylist)){
		identified = LocateHash(mylist,p.saddr,p.daddr,p.source,p.dest);
		if (identified == NULL){			
			flowNo=flowNo+1;
			mylist =    InitializeFlow(mylist,p.saddr,p.daddr,p.source,p.dest,TimeStamp.QuadPart,flowNo);
			identified = mylist;
			if (debug == 1) printf("in null Flow =%d %u %u %u %u",identified->fl.flowID, p.saddr,p.daddr,p.source,p.dest);			
		}
		else{				
			identified->fl.num_of_packets += 1;				
			identified->fl.last_time = TimeStamp.QuadPart; // flow time not packet time			
		}
	}	
	else{ 
		flowNo=flowNo+1;
		mylist = InitializeFlow(mylist,p.saddr,p.daddr,p.source,p.dest,TimeStamp.QuadPart,flowNo);	
		identified = mylist;
		if (debug == 1) printf("new Flow =%d %u %u %u %u",identified->fl.flowID, p.saddr,p.daddr,p.source,p.dest);		
	}		
	// Delay packet
	delay = Rainbow(identified,rand)*1000; 		
	
        QueryPerformanceCounter(&EndingTime);	
	ElapsedMicroseconds = getelapsedtime(StartingTime,EndingTime,Frequency);		
	delay = (delay - ElapsedMicroseconds.QuadPart);	
	if (delay<0) delay = 0;	
	uSleep(delay);	//delay in ns	
	//WinDivertHelperCalcChecksums(packet, packet_len,WINDIVERT_HELPER_NO_REPLACE);
	// Re-inject Packet
         if (!WinDivertSend(divert, pac, pac_len, &add, NULL))
	{
		fprintf(stderr, " warning: failed to reinject packet (%d) ", GetLastError());
		printf(" DstAddr=%u.%u.%u.%u",(p.daddr >> (8*3)) & 0xff,(p.daddr >> (8*2)) & 0xff,(p.daddr >> (8*1)) & 0xff,(p.daddr >> (8*4)) & 0xff);
		return 1;
	}	
	return 0;
	     
}

**Comment by basil00** [comment]
The problem is that you are passing the address `add` and packet buffer `pac` to the new thread, and then immediately call `WinDivertRecv` again in the main thread loop.  There is nothing stopping `WinDivertRecv` from overwriting the `add`/`pac` memory (with the next packet) before the `divert` thread has finished processing, and this probably explains your errors.

Also, created a new thread each time a packet is received is very inefficient.  It is better to create multiple threads at startup, and have each thread process packets independently, like the `passthru` sample program.

**Comment by sardasanat** [comment]
Yes. Thats correct. But then why do ICMP packets (ping) does not give any errors ?

I have also implemented multiple threads at startup approach. Issues with this approach is,
  
1. I don't want packet to wait for a thread to be free, as that adds more delay to the packet. Only delay assigned to the packet should be from the "delay algorithm". If the packet has to wait, it accumulates more delay. To get as accurate delay possible, I also subtract the thread execution time from final delay, before delaying the packet.
2. I dont know what are the maximum threads I ll require ? Each packet should get a thread immediately as it is received. That is no packet should wait for thread. I divert all outbound packets. Outbound packets are variable at a any given time.

e.g outbound transfer of 16MB file (~11900 packets) with 100 threads takes ~2:34 minutes and with 200 threads takes ~1:01 minutes for same amount of delay per packet from delay algorithm. Thus here am not sure what my maximum thread value should be and whether even 200 is enough. Wireshark, should atleast show me close constant approximate value to delay assigned by delay algorithm to each packet. But is variable.

Also, is there a function call, to find out number of packets queued at any given time and the packets dropped from queue?

**Comment by basil00** [comment]
> But then why do ICMP packets (ping) does not give any errors ?

Probably because of the space between packets is long enough such that the buffer does not get clobbered.

> 100 threads 

Are using a 100+ core machine?  Either way, first fix the memory buffer bug otherwise the timings are not very meaningful.

> Also, is there a function call, to find out number of packets queued at any given time and the packets dropped from queue?

No, such functions do not exist in the API.

**Comment by sardasanat** [comment]
Tested ICMP packet input rate with 01, 0.2, 0.5 msec per packet.

100 threads is using different code that of your passthru example, where multiple threads are created at startup and each divert function has a WinDivertReceive function. So each thread has local copy of packet buffer.I am using a 4 core ( per core 8 logic processors) 64 bit machine

**Comment by sardasanat** [comment]
Issue with passthru example is that threads would process and re-inject packet before the packet that was received earlier and was being processed by another thread. This significantly seen if the rate at which packets are received are significantly higher.

**Comment by TechnikEmpire** [comment]
@sardasanat You're spawning 100 threads against 8 logical cores? What are you trying to accomplish except to severely degrade performance by sleeping and resuming 100+ threads?

**Comment by sardasanat** [comment]
I am trying to find the limit i.e maximum no of threads I need to create at startup so that no packet have to wait for a thread to process it. In other words, thread is available to process packet immediately. So for couple of threads and high packet input rate, packet processing time increases and my application requires restricting packet processing time to certain time value.

**Comment by TechnikEmpire** [comment]
@sardasanat But if you only have 8 logical cores, you realize that you cannot possibly have anymore than 8 threads executing concurrently, right? It makes no sense in this case to start so many threads, you're going to be forcing 92 threads at any given time to sleep and then awoken again at some indefinite time in the future. This is extraordinarily expensive, especially multiplied by 92. 

Further, have you actually identified a bottleneck with processing packets that is a huge issue? Note that you're definitely going to take a performance impact even if you don't do any processing, because you're having the WinDivert driver capture and then push/pull packets back and forth from user space to kernel space. Right there you're taking a hit that cannot be avoided at all, unless you feel like writing your own kernel mode driver.

I believe you're creating an issue where there absolutely isn't one. The fact that your line of thinking here is "threads are great, let's make zillions of them" tells me that you're prematurely optimizing and need to do more research on the subject as a whole. Not meaning to sound rude, I'm trying to help you.

**Comment by sardasanat** [comment]
@TechnikEmpire Thanks for your reply. All comments are welcome.
  8 threads executing concurrently, right?
How do you know that ? Can you clarify. Earlier I read,and as per it considered 32 as there are 4 cores. Then there is reference here, 
http://superuser.com/questions/759206/how-many-threads-are-concurrently-executed 
and here where 2nd responder says concurrent threads depends on other factors,
http://stackoverflow.com/questions/4828296/how-many-threads-can-i-run-concurrently
So it is slightly unclear. The affinity of my application process in Task Manager is auto set to use all logical CPU's of all processors. 

The objective of showing tests with higher threads (100) was I was getting higher data transfer. But as rightly pointed its meaningless as memory buffer was being overwritten. 

have you actually identified a bottleneck 
As I mentioned before, packets were being re-injected before the packets that were received earlier. Packet shouldn't be re-injected out of order. Again it was due the memory buffer bug.

performance impact even if you don't do any processing
Yes, currently filter performance impact is not of concern. I hav'nt tested others to compare too. Currently just require packet filtering and process. If my application requires to consider performance of filter, will test others. Using windivert, as its quite convenient.

"threads are great, let's make zillions of them"
No. If task can be achieved in lesser threads, why require more. Question is how would I know the right no of threads as in my earlier "bugged" code, higher seemed better. Infact, most of testing I did with less than 32 threads.

Ideally, I require 0 packets or as less as possible packets to get queued. Dont want queuing delay. I have figured that the delay, my app adds should be much  less than (<<) packet input rate to the filter. As delay from my app increases with increase in no. of packets received overtime, it increases thread execution time and thereby reduces data transfer speed.

**Comment by TechnikEmpire** [comment]
@sardasanat The guy answering the question you reference has no idea what he's talking about. You don't multiply number of cores by logical processors. Number of cores represents the number of physical cores. Hypherthreading is a technology that enables a single physical core to act as two logical cores. If you have a 4 core processor with hyperthreading, you have 8 logical cores. A logical core cannot possibly (meaning absolutely physically impossible, at least with our technology) be executable execute two threads simultaneously. 

This is one of pillar features that the kernel brings to the OS, the ability to correctly and efficiently schedule threads to pause, sleep and resume. There are hundreds to thousands of threads spawned by processes on your computer at any given time (task manager will show you how many) but only 8 of them (with a typical intel processor) are doing anything in any given moment of time. The rest are blocked and released according to:

A) The kernel scheduling
B) Per-application introduced blocking (locking).

So you can spawn threads till the cows come home, once you surpass the number of logical cores you're probably hurting rather than helping. This however greatly depends on the task that you're performing, and there is no one right answer. See:

http://stackoverflow.com/questions/902425/does-multithreading-make-sense-for-io-bound-operations

http://stackoverflow.com/questions/1239918/what-is-the-optimal-number-of-threads-for-performing-io-operations-in-java

I would start off with making the number of threads equal to the number of cores and see how that works for you. Then maybe halve it. Also you could try potentially increasing the number of cores a bit if you're using the Ex functions, but I'm not sure about that (not much experience with overlapped IO, maybe @basil00  can chime in on that). Definitely don't throw dozens or hundreds of threads at it, and make sure you use the SendEx function without any supplied overlap to simply fire and forget your packet once you're done with it.
