### ISSUE TITLE
How to capture mirrored packets in windivert application 

### ISSUE THREAD

**Issue by sardasanat** [basil00/Divert#67]
Using forward layer and wireshark, windivert app receives packets, but see more packets than mirrored. Without wireshark, it doesnt receive at all. In network layer, windivert app hangs the PC. I have tried quite few things and not sure how to go about. I think its similar issue to the one open on "switch port mirroring" .

**Comment by sardasanat** [comment]
Currently, in forward layer, by changing interface number and packet direction. (Directing packets to loopback interface) Although I get " failure to reinject packet 1231" , but  am able to capture mirror packets properly. Also I still have to run wireshark concurrently, to receive mirrored packets in windivert app.

**Comment by TechnikEmpire** [comment]
@sardasanat Please consider posting questions on how to use/do things to somewhere like stackoverflow. Basil is on there and might even pick up the question if you tag it correctly. As someone who maintains repositories of his own, it's a real pain the arse when people open bug tickets because they can't figure out how to do something. Consult the documentation, ask on stackoverflow and then if you're really sure there's an issue with the library and not with your own code, open a ticket.

@basil00 Feel free to tell me to shut up, not trying to step on your toes, just trying to help everyone, including sardasanat.

**Comment by sardasanat** [comment]
@TechnikEmpire I dont think you understand (probably you havnt read properly) and your comments aint helping (which you claim). Infact I find it funny that someone thinks, one can post an issue like this without referencing the document, similar issues (closed and open) and related posts on stackoverflow.  For your understanding, let me elaborate, I bumped on an issue, which is same as open issue #36,  closed issue #34 ( as PC doesnt need to be configured as router, to capture mirrored packets, but if have to use windivert, have to use forward layer and thus PC required as router which requires another interface, config subnet, and complex filter/handles so that non-mirror traffic is not affected ) and a known issue in documentation (re-injecting unmodifying packets- leading to infinte loop, as I receive more packets then mirrored). Using loopback interface (which I mentioned prior) and changing packet direction ( a suggested in many threads)  infinite loop is sorted, but not the concurrent use of wireshark/winpcap or issues related to non-mirrored traffic. 

Another funny assumption is that someone thinks, users posting issues here think they have bug free codes.

In any case, to post (or repost a similar existing open issue), was to know if there were an alternative or progress as found no recent comments. As a user, not in the buiz, of developing own filter driver or compiling and modifying same. So called helpful comments are discouraging.

**Comment by TechnikEmpire** [comment]
@sardasanat Both of those referenced issues have either been closed or had comments made by the library author where theories about the cause are implied, and it boils down to the library inheriting behaviors from the WFP, the system on which the library is built. Also there is a suggestion backed by strong evidence that WinPCap is interfering in both cases.

Have you done any reading about WFP in general? Have you googled "WFP mirrored packets issue"? Have you googled what error code 1231 is? Do you know where the error code that WinDivert gives you comes from? 

"ERROR_NETWORK_UNREACHABLE" - This can mean a number of things, have you googled known causes of this error? I'll help you. For one, you can get this error when you're trying send or receive packets across isolated interfaces. You'll get this error, for example, if you try to pull a packet out of loopback destined for loopback, and push it across to a public facing interface.

I'm not going to expand on that any further, I'm just trying to point out what's happening here: you're making at **MINIMUM** one critical mistake and before making sure that you've worked all of your own bugs out, you're spamming the library author and all other 48 people subscribed to this repository with accusations of bugs. 

Now, you were ignorant to me and I'm not going to be ignorant back, I'm just going to simply explain to you that this is ignorant behavior. It's ignorant to force 48 people who care about this project to read your poorly written messages that don't even offer so much as a single shred of source code demonstrating an issue to test. 

You're complaining about things not working the way you expect them to and basically asking for someone to fix **your** problems in code. Worse still, you're using the bug reporting system to do this. Even worse still, when someone tries to politely direct you to stop doing this and use the proper channels to get free programming lessons and advice, you go wild with verbal abuse.

WinDivert sits on top of Windows Filtering Platform. My advice would be that from now on, google "Windows Filtering Platform + MY_ISSUE" at least over 9000 times before opening bug tickets.

**Comment by TechnikEmpire** [comment]
@sardasanat I just realized that you also discarded my remarks because I'm just "just a user" and not "in the biz of developing.."

https://github.com/TechnikEmpire/Divert.Net

https://github.com/TechnikEmpire/HttpFilteringEngine

https://github.com/TechnikEmpire/StahpIt-WPF

I don't claim to be some brilliant programmer, but I think I have a clue about what's going on. Want to know how I have a clue about what's going on? Because I shut my mouth and open my ears when I know that I don't know what I'm talking about, and that the person who is speaking does know what they're talking about. If I walked around acting cocky and verbally assaulting everyone who tried to educate me, I'd be.. gee I dunno.. blabbing away in ignorance on the internet.

**Comment by sardasanat** [comment]
@TechnikEmpire I still think you dont get it. 

"As a user, not in the buiz, of developing own filter driver or compiling and modifying same"  
I am talking about myself. I am the user not the one developing. So I am ok to use any filter that works with my overlaying application, but cannot work on filter itself . (outside my scope)

"Both of those referenced issues have either been closed or had comments made by the library author where theories about the cause are implied, and it boils down to the library inheriting behaviors from the WFP, the system on which the library is built. Also there is a suggestion backed by strong evidence that WinPCap is interfering in both cases"  
Thus was the intention, to know if any progress or alternative.

"Have you googled what error code 1231 is?" 
Yes. But as I said, its irrelevant, as I receive my mirrored packets between WindivertReceive and WindivertSend. So not required (optional) to send.

"Have you done any reading about WFP in general?" 
Yes, but not worked out in detail, outside my scope. 

"My advice would be that from now on, google "Windows Filtering Platform + MY_ISSUE" at least over 9000 times before opening bug tickets. " 
No, outside my scope :) 

"acting cocky and verbally assaulting everyone"
Wow. 
"blabbing away in ignorance on the internet" . 
You can reach me in real. +65 84202876

About your remaining comments, dont know your persuasion (probably misplaced passion). All the best to you with your work.

**Comment by TechnikEmpire** [comment]
@sardasanat Comments withdrawn, forget I ever replied to you. Blocking you now because you're either A) very terrible at English, which is why your comments are appearing as rude or B) deliberately trying to be rude and then hiding behind poor English to excuse it.

**Comment by basil00** [comment]
> Without wireshark, it doesnt receive at all.

I do not know the cause of #36.  I can only speculate that the installation of a NDIS protocol driver causes Windows to retain the mirrored packets it would otherwise discard; and thus such packets become visible at the WFP network layer.  It is possible that mirrored packets normally appear at the `FWPM_LAYER_*_IPPACKET_*_DISCARD` layer (which WinDivert does not support), but I have not tested that theory.

> In network layer, windivert app hangs the PC.

This sounds like an infinite loop (was this confirmed?).

Re-injecting mirrored packets sounds problematic anyway.  Mirrored packets are already copies so you cannot really "filter" them, i.e. you cannot block the original packet.  The best you can do is to attempt to interrupt or hijack the connection somehow, e.g. by crafting TCP RSTs.
