### ISSUE TITLE
How to validate all checksums?

### ISSUE THREAD

**Issue by satnatantas** [basil00/Divert#73]
I want to modify packets but I do not want to validate them if they were not valid to not damage the receiving applications.

Is there a convenient way of doing it except copying packet, updating checksums in a copy and comparing all the checksums 1 by 1?

**Comment by satnatantas** [comment]
Or, should I just `memcmp` the original packet and the packet with updated checksums?

**Comment by ffalcinelli** [comment]
Your requirements aren't so clear to me... If you edit any header then checksum for that header will not match with the original packet. There's [WinDivertHelperCalcChecksums](https://reqrypt.org/windivert-doc.html#divert_helper_calc_checksums) function that will recompute your checksums, and if you are sure some of them are already right, you can exclude those (e.g. suppose you just edit IP header you don't need to recompute TCP ones) to save some CPU.

Just call this function before sending with [WinDivertSend](https://reqrypt.org/windivert-doc.html#divert_send) should be enough.

As a suggestion since I'm not the owner of this repo, you could try to open this kind of questions on [StackOverFlow](http://stackoverflow.com/questions/ask) so that you can get better support from community. IMHO github issues should be for issues and proposals.

**Comment by satnatantas** [comment]
@ffalcinelli there is a special label "question" here on GitHub.

I assume that a packet may arrive damaged. Will that be detected before diverting by the WinDivert driver? If it is damaged and if I modify it before knowing whether it is damaged or not I am validating errors.

**Comment by ffalcinelli** [comment]
Yes, that was just to get to a broader audience, I'm not saying you can't (and I'm not even qualified to do so). 

Anyway, not proved but I think you can get only 2 scenarios on receiving packets with wrong checksums: the network stack drops them silently as part of normal network control flow or you can drop them by code. 

In first case, you should obtain retransmissions or packets silently dropped out without even noticing, your application won't receive damaged packets.

By using WinDivert I think you can make decisions on those packets, they're removed from the stack and you can choose to reinject them or not. So when receiving a packet you could read and store its checksums, call [WinDivertHelperCalcChecksums](https://reqrypt.org/windivert-doc.html#divert_helper_calc_checksums) and compare the result on the modified packet. If they match, then pass the packet to send method to reinject it in the network stack, otherwise just drop it.

**Comment by basil00** [comment]
> Is there a convenient way of doing it except copying packet, updating checksums in a copy and comparing all the checksums 1 by 1?

The checksums for packets returned by `WinDivertRecv` will either be valid or zero.  It will be zero only for outbound packets and where checksum offloading is enabled.  If Windows receives an inbound packet with an invalid checksum, the packet will be discarded before it reaches WinDivert.

**Comment by satnatantas** [comment]
@basil00 thanks!
