### ISSUE TITLE
Inject/Redirect packets to the loopback interface (127.0.0.1)

### ISSUE THREAD

**Issue by mbg033** [basil00/Divert#82]
Is there a way to redirect packets to the local proxy running on loopback interface (127.0.0.1)?
I'm trying to implement transparent proxy, but I have a restriction so proxy should be listening on loopback (127.0.0.1) interface only.
Currently filter is
```
(tcp.DstPort == 80 or tcp.DstPort == 443 or tcp.SrcPort == <proxy_port>)
```

What I've tried already (for the packet captured from web browser when web browser performs TCP connection to remote address)
1. set dst address = 127.0.0.1, dst port = <proxy_port> and direction = WINDIVERT_DIRECTION_OUTBOUND - WinDivertSend fails with error 1214 (The format of the specified network name is invalid).

2. set dst address = 127.0.0.1, dst port = <proxy_port> and direction = WINDIVERT_DIRECTION_INBOUND. WinDivertSend returns without error but no replies from 127.0.0.1 received.

3. same as (2), but also change addr.IfIdx = 1 and addr.SubIfIdx = 1, WinDivertSend returns without error but no replies from 127.0.0.1 received

4.  same as (2), but also change addr.IfIdx = 0 and addr.SubIfIdx = 0, WinDivertSend returns with error = 87 (ERROR_INVALID_PARAMETER)

5. Same as (2), but also change addr.IfIdx = 1 and addr.SubIfIdx = 0. WinDivertSend returns without error but no replies from 127.0.0.1 received

if I start proxy listening on INADDR_ANY, everything works fine, but I need proxy listening on 127.0.0.1 only.

Also tried to modify [streamdump example](https://github.com/mbg033/Divert/blob/develop/examples/streamdump/streamdump.c) so it listens on INADDR_LOOPBACK instead of INADDR_ANY - it stops working as well.

**Comment by TechnikEmpire** [comment]
@mbg033 I doubt this will work because you'll be trying to push and pop packets to and from private address space to public. You should simply be looking for outbound only packets that are destined for 443 and 80 and forcing them through to the proxy. Also on the proxy side you're going to need to look for incoming, yet non-http connections because this definitely will happen and your proxy will kill all kinds of apps unless you have a passthrough mechanism. The passthrough mechanism should simply schedule async reads and writes on non-http connections, letting the local and remote applications handle IO op ordering unless you're going to specifically identify each non-http protocol.

**Comment by TechnikEmpire** [comment]
@mbg033 Any reason why you must have the proxy bound to 127.0.0.1?

**Comment by mbg033** [comment]
@TechnikEmpire mostly the reason to avoid blocking this proxy by antivirus/firewall

**Comment by basil00** [comment]
> Also tried to modify streamdump example so it listens on INADDR_LOOPBACK instead of INADDR_ANY - it stops working as well.

That's not surprising.  The streamdump sample works by swapping the `SrcAddr` and `DstAddr` of each packet diverted to and from the local proxy, and swapping them back again on the reverse path.  This is a simple trick that makes it easy to track IP addresses.  However, if you want to divert to a local proxy listening on localhost, you must overwrite one (or both?) of these IP addresses with 127.0.0.1 instead, which means you've lost information.  It should be possible to do this, however, you need to invent your own method to correctly restore the IP addresses for the reply packet, and possibly network interface numbers too.  AFAIK, nobody has attempted to implement this before.

**Comment by mbg033** [comment]
Yes, I do understand it will require address/port mapping, but right now the point is I can't see any SYN+ASK TCP segments after SYN packet sent by the app redirected to the proxy running at INADDR_LOOPBACK.
I added debug dumps to the [streamdump example](https://github.com/mbg033/Divert/blob/develop/examples/streamdump/streamdump.c)
and I only see outgoing SYNs redirected to the local proxy, but not SYN+ASK replies from the proxy:

```
$ streamdump.exe 80
captured outbound PORT ---> PROXY
[192.168.1.109:56613 -> 107.21.206.81:80, seqnum: 3364122320, asknum: 0, ask 0 psh 0 rst 0 syn 1 fin 0]

Sending:
[107.21.206.81:56613 -> 127.0.0.1:34010, seqnum: 3364122320, asknum: 0, ask 0 psh 0 rst 0 syn 1 fin 0]

captured outbound PORT ---> PROXY
[192.168.1.109:56613 -> 107.21.206.81:80, seqnum: 3364122320, asknum: 0, ask 0 psh 0 rst 0 syn 1 fin 0]

Sending:
[107.21.206.81:56613 -> 127.0.0.1:34010, seqnum: 3364122320, asknum: 0, ask 0 psh 0 rst 0 syn 1 fin 0]
```

**Comment by basil00** [comment]
I am not sure of the exact reason -- however, it appears that you are injecting an inbound packet with a localhost destination address and a public source address.  I think it is likely that such a packet will be discarded.

**Comment by basil00** [comment]
No need to keep this open.

**Comment by GreatFireWall** [comment]
@mbg033 Try modify ```ip.SrcAddr``` and ```ip.DstAddr``` to ```127.0.0.1``` both.

**Comment by fernando-neves** [comment]
Has anyone managed to do this?

**Comment by da-kami** [comment]
@mbg033 were you able to achieve to re-route the packets to loopback back then? 
I am working on the same problem and would be keen to get some more insights. Simple re-direction to localhost in the dstaddr is not enough.

**Comment by da-kami** [comment]
After collecting a lot of information I can confirm: 
It is possible to re-direct packets to a proxy listening on loopback.

Note: I have not used the steamdump example, but I have a packet redirect and proxy solution built in Rust, the redirector on Windows uses WinDivert (using https://docs.rs/windivert/latest/windivert/)

If anybody else comes across this ticket here is how I achieve packet redirect locally:

Modify "request" packets (i.e. outbound but not coming from the proxy port):

- Set both src and dst address to `127.0.0.1`, keep a mapping of src-port to the original dst and src-port to the original src address
- Change the dst port to the proxy port

Note: In the original "trick" we change the packet direction from outbound to inbound. That is not possible when directing packets to loopback, so the direction of the packet directed to the proxy has to be outbound.

Modify "response" packets: 

- Lookup the original src and dst address by dst port for packets that comes from the proxy port
- Set the original src and dst for the packet to match what the application expects, i.e. dst is the original src and src is the original dst (i.e. the remote) addr.

This setup enables a locally running transparent proxy. 

Note: I additionally have a separate locally running interception server for handling HTTPS and simulating CONNECT requests against the proxy; but that is irrelevant for the packet redirection. To avoid intercepting traffic related to the interceptor / proxy I apply a process ID based filter.

**Comment by charankamarapu** [comment]
hey @da-kami can you share your code if possible..?

**Comment by da-kami** [comment]
@charankamarapu unfortunately the codebase I'm working on is not open source so I cannot share the code.
But I'm happy to help if you have specific questions.

**Comment by charankamarapu** [comment]
@da-kami I was actually doing a similar thing using rust. All I have done is change the packets(tcp) src and dst address to 127.0.0.1 and dst port to my proxy port. and I have a proxy which is listening for tcp connections on that port. But I am not receiving  any traffic over it. Am I missing anything..? I have observed that there is some loopback variable in the address of windivert - https://docs.rs/windivert/latest/windivert/address/index.html which is false, may be that is causing the issue..? Any idea over this

**Comment by da-kami** [comment]
@charankamarapu  I did not modify the loopback variable (loopback flag).
Are you re-calculating and setting the packet checksums correctly?

We use [smoltcp](https://github.com/smoltcp-rs/smoltcp) for the packet modification (which is a bit of an overkill because it's a complete TCP stack, but it is one of the better maintained libraries out there for packet modification).
Not sure if you're using a lib for the packet modification; smoltcp has helped me "getting it right". With this low level network code it's either completely right or no packets at all unfortunately... Hard to debug.

**Comment by TechnikEmpire** [comment]
Guys this was answered in 2017. You can't have the src and dst addresses be from networks that are unreachable to one another. What you're doing here isn't packet modification, it's full blown packet crafting. Make sure you're using WinDivert in a way that discards the captured packet so when you get it, use the headers to modify the payload and then wholesale inject the payload with a proper handle like it's a brand new packet.

Also I just have to say, this is a lot of overhead to feed a proxy. Unless your WAN firewall is absolute trash, there's no reason not to bind to your LAN address within the computer's ephemeral range. Just bind to 0.0.0.0:0.

**Comment by charankamarapu** [comment]
@da-kami Even I thought of using smoltcp but as you said yep that is an overkill. Yeah I have missed the checksum part, Let me correct that and try again.

**Comment by da-kami** [comment]
> Guys this was answered in 2017. You can't have the src and dst addresses be from networks that are unreachable to one another. 

I'm not sure I can follow.

> What you're doing here isn't packet modification, it's full blown packet crafting. Make sure you're using WinDivert in a way that discards the captured packet so when you get it, use the headers to modify the payload and then wholesale inject the payload with a proper handle like it's a brand new packet.

I did not have to do that, modifying the packet ip-address and port and re-injection is sufficient.

> Also I just have to say, this is a lot of overhead to feed a proxy. Unless your WAN firewall is absolute trash, there's no reason not to bind to your public address within the computer's ephemeral range. Just bind to 0.0.0.0:0.

Binding to `0.0.0.0:0` on Windows causes all kinds of security related issues. I'm not a Windows fan, but that's what the product is built for... 
Keeping the traffic on loopback makes it easier because then WinDefener (...) don't complain. 
Firewall rules can help, but they make the setup more complicated. 

I would argue that a transparent proxy is always some form of overhead.

**Comment by TechnikEmpire** [comment]
> > Guys this was answered in 2017. You can't have the src and dst addresses be from networks that are unreachable to one another.
> 
> I'm not sure I can follow.
> 
> > What you're doing here isn't packet modification, it's full blown packet crafting. Make sure you're using WinDivert in a way that discards the captured packet so when you get it, use the headers to modify the payload and then wholesale inject the payload with a proper handle like it's a brand new packet.
> 
> I did not have to do that, modifying the packet ip-address and port and re-injection is sufficient.
> 
> > Also I just have to say, this is a lot of overhead to feed a proxy. Unless your WAN firewall is absolute trash, there's no reason not to bind to your public address within the computer's ephemeral range. Just bind to 0.0.0.0:0.
> 
> Binding to `0.0.0.0:0` on Windows causes all kinds of security related issues. I'm not a Windows fan, but that's what the product is built for... Keeping the traffic on loopback makes it easier because then WinDefener (...) don't complain.

I hate the internet so much. Raise your hand if you've built a kernel driver like WinDivert and then built software with it and sold it to a multinational. 🙋‍♂️ Ok, now sit down if you haven't.

**Comment by charankamarapu** [comment]
Hi @da-kami you can have a look at my code over here - https://github.com/charankamarapu/mitmproxy_rs/blob/e0178affadf739388d4c64902281bb5a39cc59f2/mitmproxy-windows/redirector/src/main.rs#L516

I have tracked things from wireshark 
![Screenshot 2024-10-23 090858](https://github.com/user-attachments/assets/963575a8-15dc-432f-9943-606d1e26a5e0)


I didn't concentrate on checksum because the first SYN call was able to reach the proxy, So i though may be I don't need to change anything.

1. SYN  from src to proxy is communicated properly.
2. SYN-ACK from proxy is captured and I have changed the src IP , dst IP and port. But I guess this is unable to reach the one who sent the SYN call.

Any idea where I did go wrong..?
If it is checksum, can you guide me over here..?
Is there anything else I am missing here..?

This is the packet info of SYN-ACK 

![Screenshot 2024-10-23 091415](https://github.com/user-attachments/assets/d17ef0ab-ce16-4c05-91f1-337ea8534c07)

I think the network interface shouldn't be " \Device\NPF_Loopback" right ..?

Can you help me over here..?
