### ISSUE TITLE
Signing .sys files

### ISSUE THREAD

**Issue by daotienquang16400** [basil00/Divert#85]
Hi everyone,
I follow the instructions and almost get Windivert works except that the *.sys files must be signed. I did some Google search and it leads me to these:
https://www.reqrypt.org/windivert-faq.html#q2 and
https://github.com/basil00/Divert/issues/70

The problem is I have my *.sys files signed but I still get 577 error code which is unsigned driver code. Would you guys please help me with this ? Any help would be much appreciated.
And also, basil mentioned that If I don't modify Windivert, I just need to copy pre-signed driver from binary release. I don't understand or know how to do this. Would you please be more specific and provide me with instructions if possible. I am just new to all these stuff. Thank you.

**Comment by TechnikEmpire** [comment]
@daotienquang16400 Download a binary release from https://www.reqrypt.org/windivert.html and then copy the .sys files to overwrite the ones that you've compiled.

**Comment by TechnikEmpire** [comment]
@daotienquang16400 You can read my instructions here:

https://github.com/TechnikEmpire/HttpFilteringEngine/wiki/Recompiling-WinDivert

All this process does is recompile the dll, not the .sys. The only advantage to this is that you change the version of MSVC C/C++ runtime for the newly compiled dlls. That is to say, the only reason why I do this is so that I don't have to include two versions of the C/C++ runtime from Microsoft. If you don't care about this, don't build it yourself, just use a precompiled binary release from the link above.

**Comment by daotienquang16400** [comment]
@TechnikEmpire thank you very much, you're so kind. I follow your first reply and finally get Windivert to work. I will follow your second reply if necessary in the future.

**Comment by TechnikEmpire** [comment]
@daotienquang16400 no worries. Can you close this issue? That way @basil00 doesn't have to come clean up. :)
