### ISSUE TITLE
Filter parser bug

### ISSUE THREAD

**Issue by ValdikSS** [basil00/Divert#91]
The following filter string is syntactically correct but the parser thinks it's not.
`ip and not ((ip.DstAddr >= 127.0.0.1 and ip.DstAddr <= 127.255.255.255) or (ip.DstAddr >= 10.0.0.0 and ip.DstAddr <= 10.255.255.255))`
Tried with WinDivert 1.2.0rc WDDM build.

**Comment by ValdikSS** [comment]
Stable version 1.1.8 also has a problem with `not`. It doesn't return an error and the filter looks like successfully installed, but it doesn't work properly.

**Comment by basil00** [comment]
This is not a bug per se.  The `not` operator can only be applied to simple tests like `ip` or `tcp.DstPort == 80` but not Boolean expressions.

Negation in the filter language was problematic.  E.g., given `not tcp == 80`, should this match UDP packets?  There are two reasonable interpretations:
* Yes since `tcp == 80` fails so `not tcp == 80` should succeed;
* No since `not tcp == 80` is equivalent to `tcp != 80` which fails.

WinDivert uses the second interpretation for `not`.  However, since WinDivert version 1.2 *conditional expressions* are supported which use the first interpretation.  You can therefore rewrite your filter as:

    ip and ((ip.DstAddr >= 127.0.0.1 and ip.DstAddr <= 127.255.255.255) or (ip.DstAddr >= 10.0.0.0 and ip.DstAddr <= 10.255.255.255)? false: true)

**Comment by ValdikSS** [comment]
I see. Then I believe 1.1.8 is buggy in the terms that it accepts such filter with `not` but works incorrectly.

**Comment by basil00** [comment]
Possibly 1.1.8 is buggy.  `WinDivertOpen` should fail with that filter string.  I will investigate.

**Comment by basil00** [comment]
OK I tested it and can confirm that `WinDivertOpen` accepts the filter without an error.  It seems this is a rather silly bug in the WinDivert 1.1.8 filter parser, which (surprisingly) has gone unnoticed for a long time.

Version 1.2.0 does not have this bug since it uses a new parser.

I am not sure if I will fix.  Probably best to just deprecate version 1.1.X and officially switch to 1.2.Y, which is overdue anyway.
