### ISSUE TITLE
DNS RESOLUTION  with Divert

### ISSUE THREAD

**Issue by topeawolwo** [basil00/Divert#94]
****Am working with Visual Studio 2015.

I do want to know working with divert, can i achieve the following :

Which of the Divert function can i extend for packets to be modified in  such a way that it would listen on port UDP 53 or  TCP. Intercept the packets, carry  out a  DNS RESOLUTION string name to IP conversion and redirect them to another DNS SERVER ).

My question is this  can divert  be used for DNS RESOLUTION, am aware that i can achieve packet interception and redirection, but i want DNS RESOLUTION. 

Which of the functions would do?
looking forward to your answer**

**Comment by TechnikEmpire** [comment]
@topeawolwo Are you stuck in C/C++ land because that's going to require either A) a DNS library to properly craft packets or B) you to craft your own DNS packet construction and believe me you don't want to do that.

The code for WinDivert to pass DNS packets around is trivial, the code to actually handle them properly is not.

[Libcrafter](https://github.com/pellegre/libcrafter) has some utilities that might be helpful in doing this.

**Comment by basil00** [comment]
@topeawolwo yes you basically use WinDivert to divert DNS requests to a different resolver, then divert the responses in the other direction; basically as a DNS proxy.  Alternatively the program itself can handle the intercepted DNS requests.  [Tallow](https://github.com/basil00/TorWall) does something like this although it handles DNS requests directly and only handles the common cases.
