### ISSUE TITLE
Incorrect traffic handling in 1.2.0 rc

### ISSUE THREAD

**Issue by ValdikSS** [basil00/Divert#98]
Hello.
Some GoodbyeDPI users have an issue with WinDivert 1.2.0rc. They say the websites won't load at all with this version. Changing library and driver to WinDivert 1.1.8 solves the issue.
I can't reproduce it, and I don't know what steps should I do to get additional information from users' computers which have such issue.

Please refer to https://github.com/ValdikSS/GoodbyeDPI/issues/31. You can write in English.

**Comment by basil00** [comment]
Looking at the GoodbyeDPI code, it is not clear if checksums are always recalculated before injection.  This is OK for version 1.1.X, but not for version 1.2.Y, since the driver is no longer guaranteed to return packets with the correct checksums.  See the link for more information: https://github.com/basil00/Divert/wiki/WinDivert-1.2-Upgrade-Guide

I think this is most likely the cause of the problem.

**Comment by ValdikSS** [comment]
Just checked, the checksum recalculation seems fine. It works with 1.2.0rc for most users, only some users experience problems.

**Comment by ValdikSS** [comment]
To clarify, all websites stop opening right as you execute GoodbyeDPI on the machine with issue.

**Comment by basil00** [comment]
It is not clear to me that the checksum is recalculated if the first call to `WinDivertHelperParsePacket` fails, e.g. for a non-data packet.  Or is this for inbound only?  The safe approach is to just put `WinDivertHelperCalcChecksums` immediately before `WinDivertSend` and see if the problem goes away.

**Comment by ValdikSS** [comment]
Ok, I made a refactoring, now it should be more clear.
I also built EXE with `should_recalc_checksum=1` by default, let's see if it would work for that person.

**Comment by ValdikSS** [comment]
@basil00, can you please clarify if I'm using WinDivert in a correct way.
Please take a look at https://github.com/ValdikSS/GoodbyeDPI/blob/windivert-test/goodbyedpi.c
This is is a minimal filter which shows the issue. I'm only changing TCP Window Size in TCP packets without data and with SYN flag set. I recompute checksum right as I change Window Size. And it doesn't work with WinDivert 1.2.0rc MinGW/WDDK, the websites won't open.

It works if I recompute checksums for all userspace packets.

**Comment by basil00** [comment]
> It works if I recompute checksums for all userspace packets.

Yes, for WinDivert 1.2.X you need to recompute the checksum for **all** packets, even for unmodified packets.  See even the [passthru](https://github.com/basil00/Divert/blob/master/examples/passthru/passthru.c) sample recomputes checksums.

This was a change in the API from 1.1.X to 1.2.Y.  For 1.1.X there was an implicit call to `WinDivertHelperCalcChecksums` inside `WinDivertRecv`, but it was decided that this was inefficient, since most applications modify the packets anyway.  See #37 for the rationale.

If you want to be as efficient as possible, you can call `WinDivertHelperCalcChecksums(packet, packet_len, WINDIVERT_HELPER_NO_REPLACE)` to recalculate checksums for *unmodified* packets.  This version will only calculate checksums that are missing.
